### ISSUE TITLE
Node replacement, missed Kobo form

### ISSUE THREAD

**Issue by annabirnbaum** [precision-sustainable-ag/On-farm-Protocols#10]
Is there a good way/ is this the best way to report that today I replaced a node, didn't have my tablet with me (unintentional), and will not be returning to the farm for maybe a month?  I need to provide the new node info, but Kobo doesn't allow for me to manually type in my node/gateways to fill out a form.  I will fill a kobo form next time I am there, but thought Brian may need the info sooner.  Does there need to be a KOBO form edit to allow manual gateway/node barcode entry or does Anna just need to not forget her tablet?   :-)

The info is: 
Gateway: 21000018
Bare Node: 18000209 (didn't change)
Cover Node: Was 18000037, changed to 18000026.
GPS points remain the same.

**Comment by brianwdavis** [comment]
I think we're always going to have to have a mechanism to handle that kind
of situation, but we really don't want people typing barcodes, so I think
this is a task that will just fall to me to do manually.

I'll try to remember to bring it up at the meeting tomorrow!

**Comment by screberg** [comment]
Close?@brianwdavis
