### ISSUE TITLE
TDR "A" and "a" have been swap in farm PQT

### ISSUE THREAD

**Issue by elhenriq** [precision-sustainable-ag/On-farm-Protocols#11]
farm pqt had the "a" sensor broken on it, by mistake now the bare node has "a" and cover node has "A"

**Comment by screberg** [comment]
Can this be closed @brianwdavis

**Comment by brianwdavis** [comment]
This shouldn't be a problem since the depth is the same for both, and the treatment label is inherited from the node, not the case of the address
