### ISSUE TITLE
GA-UAN

### ISSUE THREAD

**Issue by annabirnbaum** [precision-sustainable-ag/On-farm-Protocols#126]
[serial_20210624_084933.txt](https://github.com/precision-sustainable-ag/On-farm-Protocols/files/6717100/serial_20210624_084933.txt)

Node 491 stopped picking up the sensors on the same day I updated the nodes from 2.03 to 4.14 firmware. I was out there yesterday and couldn't find any wiring issues. Coincidence or strange firmware situation.

**Comment by saseehav** [comment]
Was it firmware? what was troubleshooted with this node that made it work for a month?

**Comment by annabirnbaum** [comment]
@saseehav I think a wire was knocked loose when updating firmware.
