### ISSUE TITLE
AL RCA weird dashboard chart/device status disconnect

### ISSUE THREAD

**Issue by annabirnbaum** [precision-sustainable-ag/On-farm-Protocols#134]
Kip and I were texting this morning about RCA.  Its weird. On device status farm Henry, there is only data from 3 nodes, 307 C2 is missing. HOWEVER in the chart view, VWC for all 4 nodes is there.  I don't seeing any obvious issue on his installation form. This set was also used in his winter testing. 

@saseehav @brianwdavis

**Comment by brianwdavis** [comment]
Wondering if I've got a bug where the winter nodes are showing up because they're installed in another set? I'll look into it.

**Comment by annabirnbaum** [comment]
looks corrected now
