### ISSUE TITLE
Temperature sensor replacement

### ISSUE THREAD

**Issue by elhenriq** [precision-sustainable-ag/On-farm-Protocols#136]
Indiana called today doing an installation today and C1 the sensors were not behaving well. We disconnected all TDRs and check one by one. We found that the temperature sensor is not working properly, so will be replaced. I will send him a replacement for it.

**Comment by annabirnbaum** [comment]
Were all the sensors not sending data because the temp sensor wasn't working??  Is this the one he called me about last week?

**Comment by elhenriq** [comment]
all the TDRs for that specific node, and yeah that was the one he called last week about

**Comment by annabirnbaum** [comment]
So did everything besides the temp sensor get fixed?  I confused what the solution for all the TDRs was.  There are others in different states with this same issue.

Anna Paulk Birnbaum

Agricultural Specialist
UGA-Department of Crop and Soil Sciences
1420 Experiment Station Rd
Watkinsville, GA 30677
C: 404-889-1688
________________________________

**Comment by elhenriq** [comment]
Yes, removing the temperature sensors fix the rest of TDR's for that node and allow them to come in
most likely the temp sensor has a short, and it causes it to not allow the other ones to read

**Comment by annabirnbaum** [comment]
Thanks!
