### ISSUE TITLE
Tablet not saving full files

### ISSUE THREAD

**Issue by miagodb** [precision-sustainable-ag/On-farm-Protocols#142]
Joey from Virginia(East) said that he couldn't see the whole printed data files in the My Files application even though he was resetting the settings (checking "log") before each node. I reset his tablet from Esper and had him print the data again and he was able to see the full file afterwards.

**Comment by saseehav** [comment]
Thanks Mia. Good reminder that resetting tablets is a good fallback and we need the whole file to print. 
Here's a link to the steps about manual printing of the node files including pointers about checking and unchecking the "Log" button to get the whole data file to print.
https://docs.google.com/document/d/1ToRG8Xt2DXDCWn5xzeg0c9WELe_7dwSoAudpl0nsLhs/edit?ts=60ccbee3
Hotline techs - are we at a point where we need to be encouraging folks to do regular printing themselves and drop into a folder?
Let's talk about how many devices need manual data logging at the water sensor meeting.

**Comment by miagodb** [comment]
Same issue again with Jared from Pennsylvania - reset his tablet through Esper and it worked.

**Comment by annabirnbaum** [comment]
I started creating an updated manual printing from nodes SOP to share with all tech a few weeks agao.  I can share this week if needed.  @Sarah ***@***.***>


Anna Paulk Birnbaum

Agricultural Specialist
UGA-Department of Crop and Soil Sciences
1420 Experiment Station Rd
Watkinsville, GA 30677
C: 404-889-1688
________________________________
