### ISSUE TITLE
Kip can't find his data after the tablet updated

### ISSUE THREAD

**Issue by miagodb** [precision-sustainable-ag/On-farm-Protocols#143]
Kip called the hotline this morning saying that he printed data off his nodes yesterday but when he went back into the My Files app this morning to send the data files, nothing was in the folder. Kip mentioned that the tablet updated last night and thinks that might be the cause. He is wondering if there is any way to recover the files or if he has to go back to the fields and reprint the data.

I guided him through how to save the data in another folder from now on in the USB Terminal settings but told him that I'm not sure if there is a way to recover the data. He is going to go back to his fields next week to reprint but still would like to know if there's any way to recover the past files.

**Comment by annabirnbaum** [comment]
This is why we need to give people the option to download data using arduino.

I know it isn't available on android but we could tell people they can use their laptop if they want a more confident way to download data from nodes.

Anna Paulk Birnbaum

Agricultural Specialist
UGA-Department of Crop and Soil Sciences
1420 Experiment Station Rd
Watkinsville, GA 30677
C: 404-889-1688
________________________________
From: miagodb ***@***.***>
Sent: Friday, July 16, 2021 10:31 AM
To: precision-sustainable-ag/On-farm-Protocols ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [precision-sustainable-ag/On-farm-Protocols] Kip can't find his data after the tablet updated (#143)

[EXTERNAL SENDER - PROCEED CAUTIOUSLY]


Kip called the hotline this morning saying that he printed data off his nodes yesterday but when he went back into the My Files app this morning to send the data files, nothing was in the folder. Kip mentioned that the tablet updated last night and thinks that might be the cause. He is wondering if there is any way to recover the files or if he has to go back to the fields and reprint the data.

I guided him through how to save the data in another folder from now on in the USB Terminal settings but told him that I'm not sure if there is a way to recover the data. He is going to go back to his fields next week to reprint but still would like to know if there's any way to recover the past files.

**Comment by saseehav** [comment]
@screberg @brianwdavis can I have a tech intern look into new apps for the tablets to 1. replace USB serial monitor and 2. do file storage for Android. 3. practice putting sd cards into the Samsung tablets so files go on this sd card for easy access and storage so it doesn't get wiped.

**Comment by miagodb** [comment]
Both Cynthia (Virginia West) and Jared (Pennsylvania) have also called within the last week saying that they can't find their files after they print and save data from the node. I had them customize their settings so that they can save their files in a different folder. Jared had to restart his tablet before this worked but it did eventually work for both of them.

**Comment by saseehav** [comment]
@elhenriq @miagodb is file printing and saving still an issue on the tablet? do we need to update the protocol with information about this?

**Comment by miagodb** [comment]
I'm not sure if it's still an issue. I just had them change the location their files saved and this solution worked. Is the folder that all files save this year going to be the same as last year (...de.kai... > files) or will it be in an empty folder? There are a lot of data files from last year stored in the "files" folder so we have to scroll through a lot to find our newest printed files.
