### ISSUE TITLE
Gateway Status Lights not Coming On 

### ISSUE THREAD

**Issue by miagodb** [precision-sustainable-ag/On-farm-Protocols#144]
Lindsey from VT is at POG trying to get her gateway to connect to her nodes and the dashboard. She said that the green status lights don't come on when she turns on the gateway. I told her to disconnect the solar panel hub and reconnect it. Lindsey noticed that the wires were messed up inside the green hub and she stripped and rewired the solar panel. When she plugged it back in, she could see that the battery voltage read about 1.5 Volts.  I told her to wait a little while for the solar panel to charge the battery and then connect back into the gateway to see if it would send a time update to the node. If the gateway starts talking to the dashboard again, Lindsey will reconnect her nodes on Monday.

**Comment by alondrathompson** [comment]
@miagodb You're correct. The status light wasn't coming on because the battery was dead. She should also be careful that she didn't strip the wires too far back making it possible that the bare wires extending outside of the of block touch.
