### ISSUE TITLE
Missing depths in data string

### ISSUE THREAD

**Issue by annabirnbaum** [precision-sustainable-ag/On-farm-Protocols#145]
@brianwdavis 

Reoccurring issue, this set is from FL specifically.  Depths are not being reported in data string.  When this happens on GA sites, I just go in and reassign depths in field using serial usb terminal.  I am assuming we dont want new folks messing with this.  Is this something you can retroactively correct on your end?

`V2021.04.14~PSA~18000405~4.17~21.25~0~0.00~2021-7-8_6:15:00_UTC~a14Acclima TR310H2.314007572~-999~26.5~23.5~14.3~72~556~2525~b14Acclima TR310H1.014005361~-999~31.3~25.1~17.5~100~591~2790~c14Acclima TR310H2.314008105~-999~31.5~25.3~17.7~137~799~2805~d13Acclima TR310S2.114000211~-999~20.0~23.1~10.6~20~242~2175~-69`

**Comment by brianwdavis** [comment]
If the addresses ("a14Acclima", "c14Acclima") etc correspond to the depths correctly, we can try to recover that info in the database. However, in the past, sometimes they'd get moved around. So I don't know how closely we can rely on that. Has our provisioning process become standard enough that there are never mixups there?

**Comment by annabirnbaum** [comment]
From what I know there shouldn't be mix ups.  @Esleyther Henriquez ***@***.***>?

Anna Paulk Birnbaum

Agricultural Specialist
UGA-Department of Crop and Soil Sciences
1420 Experiment Station Rd
Watkinsville, GA 30677
C: 404-889-1688
________________________________
