### ISSUE TITLE
SC Sensors

### ISSUE THREAD

**Issue by annabirnbaum** [precision-sustainable-ag/On-farm-Protocols#149]
Hello,

Thank you all for the help over the past few weeks! I am still having some issues with the water sensors. I wanted to wait until I know how to address all of the issues before I go back to the farm to maximize my time in the field. Mia has helped me do some troubling shooting in the field where she walked me through getting the data off the nodes using the tablet, checking the wires, and rewiring. However, that did not solve all of the issues. She mentioned doing a firmware update might help so I wanted to touch base with you and see what you think I should do. Below is a list of the issues we are having. 
Stress Cam (16038) Wifi isn't showing up on the tablet
Two nodes do not have any wires in them (Node 18000573)
(RKT) No data for node health for Rep 1 cover and Rep 1 bare
(RKT) No data for VWC for Rep 1 cover and Rep 1 bare
(RKT) VWC for Rep 2 bare has no surface data 
(RKT) The data for VWC for Rep 2 cover stopped receiving surface data
(RKT) No data for soil temperature for Rep 1 cover and Rep 1 bare
(RKT) No data for litterbag temp for Rep 1 & 2 cover
(WBD) The gateway data is spotty. Sometimes it has data, other times it does not.
(WBD) Node health for Rep 1 bare, Rep 2 bare, and Rep 2 cover is spotty 
(WBD) No data for Node health Rep 1 cover 
(WBD) Only getting surface data for VWC Rep 1 bare
(WBD) No data for VWC Rep 1 cover
(WBD) Not getting surface data for VWC Rep 2 cover and Rep 2 bare, the data we are getting is spotty
(WBD) Only getting surface data for soil temperature for rep 1 bare 
(WBD) No data for soil temperature for rep 1 cover
(WBD) Not getting surface data for soil temperature for rep 2 bare and rep 2 cover, and the data we do get is spotty
(WBD) No data for litterbag temperature Rep 1 & 2 cover
It also looks as if the labels may be flipped on the VWC for rep 2 bare and rep 2 cover on farm WBD
Thank you in advance, 
Payton Davis

**Comment by annabirnbaum** [comment]
Hey Payton, 

I am sorry you are having all these issues.  I am going to try to help you address them all.  Worst case, I can try to schedule a time to meet you at the fields.  How far are they from Athens?


Stress Cam (16038) Wifi isn't showing up on the tablet    ​I am going to pass your info onto Akhil on the stress cam team so they can provide you expert advice with this.
Two nodes do not have any wires in them (Node 18000573).  Physically no wires?  Do you have a picture?  or are you referring to no data coming in?  575 is the other node with no sensor data coming in. 
(RKT) No data for node health for Rep 1 cover and Rep 1 bare related to wiring issue above (573,575)
(RKT) No data for VWC for Rep 1 cover and Rep 1 bare   related to wiring issue above (573,575)
(RKT) VWC for Rep 2 bare has no surface data  This is correct, no surface sensor in Rep 2
(RKT) The data for VWC for Rep 2 cover stopped receiving surface data   This is correct, no surface sensor in Rep 2
(RKT) No data for soil temperature for Rep 1 cover and Rep 1 ba.re  related to wiring issue above (573,575)
(RKT) No data for litterbag temp for Rep 1 & 2 cover  rep 1 is related to wiring issue, rep 2 doesn't have a litterbag sensor 
(WBD) The gateway data is spotty. Sometimes it has data, other times it does not.  this has been taken offline, yes?
(WBD) Node health for Rep 1 bare, Rep 2 bare, and Rep 2 cover is spotty 
(WBD) No data for Node health Rep 1 cover looks like has wiring issue
(WBD) Only getting surface data for VWC Rep 1 bare  i need to help walk you through reentering the depths on the configuration string
(WBD) No data for VWC Rep 1 cover  looks like has wiring issue
(WBD) Not getting surface data for VWC Rep 2 cover and Rep 2 bare, the data we are getting is spotty This is correct, no surface sensor in Rep 2
(WBD) Only getting surface data for soil temperature for rep 1 bare   wiring issue in rep 1 cover
(WBD) No data for soil temperature for rep 1 cover  wiring issue in rep 1 cover
(WBD) Not getting surface data for soil temperature for rep 2 bare and rep 2 cover, and the data we do get is spotty  This is correct, no surface temp in rep 2
(WBD) No data for litterbag temperature Rep 1 & 2 cover  rep 1 wiring issue, rep 2 is correct (no litterbag temp sensor)
It also looks as if the labels may be flipped on the VWC for rep 2 bare and rep 2 cover on farm WBD  ​this would have been a kobo form submission error

Good news, you only have a few main issues.  

RKT we need to address the wiring issues for 573,575.  Are wires physically plugged in to the node box?
WBD rep 1 cover 585, same question as above.  wiring issue, are wires plugged in or loose?
I will need to walk you through reentering depths for WBD rep1 bare.
fill out sensor uninstall form and then fill out install form again to correct to correct last issue in WBD.
If any VWC sensors are reding zero, they are most likely not inserted in the ground far enough. 


Anna Paulk Birnbaum

**Comment by saseehav** [comment]
This issue is ongoing - Esleyther determined that some nodes need to be plugged in and at least one node and one farm, the depths are not being graphed because the depths are reading as -999. 
This needs to be logged in a data corrections repo.

Payton - which farm code and which node was having the -999 issue with the depths not being logged correctly?

**Comment by annabirnbaum** [comment]
WBD Rep 1 bare having " the -999 issue with the depths not being logged correctly"
'

**Comment by saseehav** [comment]
-999 depth issue to be added to the water sensor protocol since it is an on-going issue @elhenriq
