### ISSUE TITLE
Site XNM, nodes 433, 380, 275, 374 not saving data regularly

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/On-farm-Protocols#150]
Example:
https://drive.google.com/file/d/1RsLPIjfuwL1Am26U9YwQh4qyT6yKHA6C/view?usp=sharing

Tauana has gone to the field to download data from the nodes multiple times, and this is an example where she printed them off the tablet on 7/13, but there is no data being printed since 6/28.

This is true for all four nodes at this site, as well as one node at another site, UHC.

Any ideas? @alondrathompson @elhenriq @miagodb @tauanafa

**Comment by brianwdavis** [comment]
All nodes at KKD are in the same situation, but they were downloaded July 19, but the most recent data strings are July 10.

**Comment by alondrathompson** [comment]
@brianwdavis Based on the file you shared, it looks like the nodes may have gotten stuck after having missed communication with the gateway more than 3 consecutive times and while trying to perform the daily handshake with the gateway (happens at 18:35 every day). This is a scenario I missed that screws up the alarms and stops the whole program. The main alarm never gets updated and remains in the past so it never triggers again. 

@tauanafa You can either: a) set the nodes to not use the gateway, or b) make sure the gateway is as close as possible to the nodes and restart everything.
