### ISSUE TITLE
VA1 Uninstallation Question

### ISSUE THREAD

**Issue by miagodb** [precision-sustainable-ag/On-farm-Protocols#155]
Joey VA East texted me asking if, when removing the sensors, it is important that the sensors stay wired together - ex. the 3 sensors from Cover 1 stay together - or can they be mix and matched? Joey mentioned that he separated a few of them and disconnected the wiring in the junction box when removing them from the field on Thursday before realizing that it could have been the wrong thing to do. He is familiar with the wiring and can connect them later, but doesn't know which TDR's belong to which rep/treatment.

**Comment by elhenriq** [comment]
TDR's should be kept together on the bundle they were shipped. If a sensor needs to be replaced, a sensor will be shipped to that team that is already address to match that configuration. 

in his specific case, sensors that came from treatment one HAVE TO STAY in treatment one, same thing for treatment two.
