### ISSUE TITLE
Barcode Scanner Misread

### ISSUE THREAD

**Issue by annabirnbaum** [precision-sustainable-ag/On-farm-Protocols#16]
The tablet barcode scanner tends to misread if not focused correctly.  This is often seen as a string of random numbers and is easy to catch (2848284).  

I was going through some previously submitted KOBO dry weight data and found several instances in which the barcode scanned incorrectly. 

Examples: 

MJZ$-A4 instead of MJZ-1-A4
JQU-2-B0 instead of JQU-2-B4
AMG-1-B4 instead of AMD-1-B4

Of course I will be more careful to make sure it is scanning correctly in the future, but wanted to make sure this is a known issue and that others know to pay attention as some of these are pretty close to correct and not super obvious.  I assume there are more in the database.

**Comment by brianwdavis** [comment]
This is really helpful, thanks!
