### ISSUE TITLE
gaps in water data

### ISSUE THREAD

**Issue by elhenriq** [precision-sustainable-ag/On-farm-Protocols#169]
I called DeAnn in KS today to check on their water sensors. 

Farm SVA keeps coming on and offline, they have been resetting manually every time it comes offline. Will download data next time it happens to make sure all data is being recorded even when not sending. 

Farm UCG needs to be checked  because cover crop treatment 2 is not registering any water sensors on it. Also cover treatment, one needs to be checked because deep sensor is reading -999

**Comment by saseehav** [comment]
@alondrathompson I thought that the gaps in the data wouldn't happen this year, but that data stored on the gateway would send when it came back online? Is that just in some cases?

**Comment by alondrathompson** [comment]
The gateway should send whatever data are received/stored. If there are no data then it either never received the transmissions or the SD card and network connection are failing. If the SD card fails to save a transmission, the gateway will immediately try to send it to Hologram instead. If they're both down, no data.

**Comment by elhenriq** [comment]
I asked them to download next time it comes offline, so we can confirm this. Like Alondra said, if the SD card is not working properly,  then it wouldn't have any data to send when it connects back online.

**Comment by kldriver** [comment]
SVA site is now in receiver mode
