### ISSUE TITLE
On-Farm Overview is basically a protocol, should be linked from protocols page on internal website

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/On-farm-Protocols#17]
Either that or we need a document that's a "how to get the experiment installed in the fall" protocol separately, but I think this would work just as well

https://drive.google.com/drive/u/0/folders/1PmT3HqUlrNiaJqxUzTGh2G0L6SJ7k6X1

**Comment by brianwdavis** [comment]
Meaning on this page https://precisionsustainableag.org/internal/on-farm/on-farm-protocols-and-data-collection/

**Comment by screberg** [comment]
I assume this can be closed @saseehav

**Comment by saseehav** [comment]
Will ask Aida to add the Overview to the protocols page
