### ISSUE TITLE
Sensor issues: LVF 1724906 (88156) MD

### ISSUE THREAD

**Issue by ethansweep** [precision-sustainable-ag/On-farm-Protocols#181]
Sensor system installed on 6/9/22
6/10/22 @9:50 am – sensors have yet to communicate with gateway
*CORRECTION: sensors did communicate with gateway, but the gateway did not communicate with the tech dashboard
Gateway Device ID: 1724906
6/15/22 @2:15 pm - sensors have still yet to communicate with tech dashboard
-- Gateway has been collecting data from most of the nodes since the install
-- One of them with a broken sensor has been turned off since the install

Gateway is not connecting to the network and not showing up on the tech dashboard
-- NIST clock update failed
-- First we pinged the nodes and got responses with complete data strings, but then the nodes wouldn’t respond to a ping ten minutes later when trying again
-- Reset the system 

Gateway pinged the nodes and received a response with complete data strings after the reset
-- Tried the cellular scouting mode after it connected to the nodes and it recognizes and turns on the SIM card, but we get an “ERROR: could not turn on cellular module”
-- Left in field and will reevaluate

**Comment by kldriver** [comment]
This site is now fully online and sending complete data

**Comment by kldriver** [comment]
This site is down again as of 08/13/2022, does it need to be reset?
