### ISSUE TITLE
Sensor issues: MJT 1724910 (87745)

### ISSUE THREAD

**Issue by ethansweep** [precision-sustainable-ag/On-farm-Protocols#182]
Last sent to tech dashboard on 5/27/22 @2:02 pm 
-- Only sending from two sensors (...0678[C2] & …1866[C1])

Bare 2 collected data, Bare 1 did not
Bare 1 - 10 cm sensor reading -999
-- Pulled up and straightened the tines, which fixed the issue
-- Added the missing temperature sensor

Bare nodes are the wrong nodes for this gateway
Gateway information:
Gateway ID = 47; Network Nodes = 66, 88, 78, 56
…0688: RID = 88, GID = 47
…0687: RID = 87, GID = 68
For some mysterious reason this node is connecting to the gateway and sending data strings to the tech dashboard, even though it has no business being connected to the gateway
…1795: RID = 95, GID = 31
…0678: RID = 78, GID=47

Find missing nodes quickly, or figure out how to change the networked nodes

**Comment by kldriver** [comment]
No chart data for this site, @ethansweep do we know what's going on with this site/ do we still need to worry about it?

**Comment by ethansweep** [comment]
@kldriver The sensor_install form is being held up on this site for no reason, which is why it's not showing up on chart view.
