### ISSUE TITLE
Sensor issues: USV 1724913 (85046) MD

### ISSUE THREAD

**Issue by ethansweep** [precision-sustainable-ag/On-farm-Protocols#183]
6/10/22 @10:05 am – Gateway sending data to the tech dashboard consistently
Node #…1857[B2] is sending -999 on all sensors 
- Check the wiring
- Reset the system

Node was damaged (possibly during sidedress) and was disconnected from the sensors
- Reattached the sensors to the node and reset the system
- The node is communicating with the sensors and data is coming through, but it isn’t showing up on the tech dashboard

UPDATE:
- Gateway is connected to all four nodes and is communicating with the gateway
- All data strings are complete

**Comment by kldriver** [comment]
rep 2 cover is not transmitting deep sensor.
