### ISSUE TITLE
Sensor issues: GYK 1724912 (87414) MD

### ISSUE THREAD

**Issue by ethansweep** [precision-sustainable-ag/On-farm-Protocols#184]
6/10/22 @9:50 am – Gateway sending data to the tech dashboard consistently
- Cover 1 – 40 cm sensor not sending any data
- Sending data strings this morning (6/13), which looked weird and similar to other broken sensor
- String of data had …65535 ~ 1260 ~ 32660…

- Cover 2 – 10 cm sensor not sending any data 
- Sending data strings this morning (6/13), which looked weird and similar to other broken sensor
- String of data had …65535 ~ 1567 ~ 326105…

Both sensors were pulled up, and the tines were straightened out. This appeared to fix the problem.
- Bare 1 - 10 cm sensor sending -999
- Pulled the sensor up and straightened the tines, which appears to have fixed the issue

Gateway stopped communicating with the gateway on 6/13/22 @12:03 pm
- Reset the system

**Comment by kldriver** [comment]
7/7/2022 briefly connected no transmission since. Signal strength is poor on all nodes and no signal indication in the chart for the gateway. Reception Issue? Is it printing data?

**Comment by ethansweep** [comment]
@kldriver I don't believe it's a cell reception issue. It was sending data reliably until we had to reset the system when we reset the system back in early June, after that it has been spotty. The nodes and gateway are collecting data.
