### ISSUE TITLE
Sensors in KS

### ISSUE THREAD

**Issue by elhenriq** [precision-sustainable-ag/On-farm-Protocols#187]

**Comment by elhenriq** [comment]
Alexis from KS called because they have 3 farms that are on receiver mode only. She drove to collect the data, but after saving it, she was not able to see that data on the tablet. (files not physically present). 

I tried to help, but couldn't figure it out. Ended up changing the root of where the files are saved on her tablet and recommend to save again and check if the files are present after she saves them. Will let me know if they appear after that.

**Comment by kldriver** [comment]
Did the files appear?

**Comment by elhenriq** [comment]
we ended up changing the storage location for the files. now is all good files have been submitted.
