### ISSUE TITLE
Farm not sending data LHM Indigo

### ISSUE THREAD

**Issue by elhenriq** [precision-sustainable-ag/On-farm-Protocols#193]
Ryan from indigo called the hotline, I got the call. He called because he wanted to check on his sensors that were not working properly in LHM. He restarted them  because he noticed only cover node 1 was sending data. After the reset, all the nodes started talking to the gateway. it kept sending data from there on.

i told him he needed to download the data from the rest of the nodes to make sure the data was still being saved on his nodes.

**Comment by kldriver** [comment]
This site went fully offline again 07/20/2022. Does it need another reset? Is it still printing data? Any other updates? @elhenriq

**Comment by elhenriq** [comment]
@ethansweep can you contact Ryan? i believe you are working with the indigo team.

**Comment by ethansweep** [comment]
@elhenriq Yes I will go ahead and contact him about this
