### ISSUE TITLE
EHC Sensor Issues

### ISSUE THREAD

**Issue by ethansweep** [precision-sustainable-ag/On-farm-Protocols#198]
Cynthia contacted me on Tuesday morning that she was going to EHC to check on some of the sensor issues.
According to the tech dashboard, the gateway had communicated with all four nodes and sent data through the network and to the database sometime in the past. One main problem is that although the gateway communicated with node #18000282 it did not send any strings of data. I had Cynthia reset the system and check the wiring on that node.
Cynthia reset the system. It had some issues pinging the nodes right away and it took several times for it to successfully link to the nodes and send a time stamp update to the dashboard.

This site has since gone down again and it's still not getting data strings for node #18000282

**Comment by elhenriq** [comment]
that sound like an issue on the node with the antenna and not having enough signal strength on it. it could be that the antenna is broken, not properly attach or an issue with objects in the way (not likely). that shouldn't stop it from collection data, though. can you have her download the data from the node itself and check that data.

**Comment by kldriver** [comment]
Do we have any follow up information on this site?

**Comment by ethansweep** [comment]
@kldriver I'll contact Cynthia and see if she can get out there to check if the data is being downloaded to the nodes and/or gateway. I'm not sure what's going on with this field. 
On the tech dashboard, this site is having a similar phenomenon to what I noticed in VT last week where the dashboard is saying that it last connected 8 days ago (July 11), but the last time stamp in the far right column is showing a date that is 13 days ago (July 6). Not sure if this is a common occurrence, or anything we should keep an eye on.
