### ISSUE TITLE
NFT not showing up in chart view

### ISSUE THREAD

**Issue by ethansweep** [precision-sustainable-ag/On-farm-Protocols#200]
Ryan called the hotline this afternoon after noticing that the surface, middle, and deep sensors were not showing up on the tech dashboard chart view. 
I went and looked at the device status and saw that the gateway was connected to all of the nodes and was sending data to the tech dashboard. I asked for the serial number of the node (18000472) and noticed that there's a -999 error message immediately following the sensor serial number. According to the PSA Water Sensor Instructional Guide this indicates that there is an error in the sensor depth, and that it was not correctly entered during the configuration. 
This needs to be corrected in the database.

**Comment by brianwdavis** [comment]
This error is recurring due to the mis-configuration, as you've noted. The only in-season fix is an periodic batch update of those rows in the database. I'll run the script and verify that NFT is working again.

**Comment by brianwdavis** [comment]
Updated ~14k rows, NFT appears to be working + others
