### ISSUE TITLE
NH holes in water data

### ISSUE THREAD

**Issue by ethansweep** [precision-sustainable-ag/On-farm-Protocols#202]
I received a call from New Hampshire today and helped them through a long list of issues they were having.
The biggest takeaway is that all their sensors went down on 21 June and didn't come back online until they reset them on 5 July. When they tried manually downloading the data there was no data collected from this time period, and even the gateway that's communicating with the gateway has the same hole.
Part of a bigger issue probably?

**Comment by saseehav** [comment]
Ethan - did you have them manually retrieve data from both the Gateway and the Nodes?

**Comment by saseehav** [comment]
@AlstonBetts can you follow up later with data collection in NH?

**Comment by kldriver** [comment]
Alston diagnosed as a gateway reception issue. He recommended putting into receiver mode. 7/14 will try to print data from Node to confirm that data is being collected.

**Comment by kldriver** [comment]
@AlstonBetts was data able to be retrieved from NH?

**Comment by AlstonBetts** [comment]
@kldriver dropped the data into the drive folder. The gateway has data from all 4 nodes saved up to 7-10 at 11:00, which was up to date

**Comment by saseehav** [comment]
What farm codes? Mark those as in receiver mode.

**Comment by kldriver** [comment]
@AlstonBetts is ERU one of the farm codes from above?
