### ISSUE TITLE
Water Sensors- AUI Indigo

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#207]
Only Rep 1 Bare is transmitting. Rep 1 Cover ran for 3 days then never reconnected. Rep 2 Bare was showing only deep sensor data, now offline. Rep 2 Cover never truly connected.

**Comment by ethansweep** [comment]
Sent Ryan Dierking the following issues and recommendations on 12 July: 

Node #18001879 (Bare 2(?)) is not sending any data except for the deep sensor. 
- Check the wiring on the other sensors and make sure everything is connected.
- Plug into the node to see if it’s collecting data from the sensors

Node #18001889 (Cover 2(?)) is not sending any data from any of the sensors
- Check the wiring on the sensors to make sure everything is connected
- Plug into the node to see if it’s collecting data from the sensors

One of the nodes is not connecting to the gateway at all
- Most likely the Cover 1 node
- Check all the wiring, and to see if the node is turned on

Reset the whole system

**Comment by kldriver** [comment]
07/19/2022 No data transmission, gateway sending time updates.
