### ISSUE TITLE
AL farm HMT keeps having issues getting disconnected.

### ISSUE THREAD

**Issue by elhenriq** [precision-sustainable-ag/On-farm-Protocols#209]
this farm has been working very well for the most part, but it has been getting disconnected lately. additionally, the middle sensor in rep 2 cover will be replaced, data coming off is very noisy.

**Comment by elhenriq** [comment]
Kip called today because this farm is not connecting to the dashboard as it should. when we started troubleshooting for some reason the gateway kept having issues while connecting to hologram. after a few tries, it did talk to hologram and started to send old data that it had stored within itself. 

the issue caused to not communicate to the server, so it wasn't able to send data even though it has excellent signal strength, additionally it gave errors on getting time updated from the NIST sever. I am not positive on what is causing this issue, but after trying to connect a few times, it came back on. and was able to connect.  this gateway keeps losing connection to hologram, which causes it to not send or receive the messages. the big issue that this creates is that field teams are not able to see the confirmation messages coming in the tech dashboard and cant make sure that their devices are in fact working. 

if you go and look at the tech dashboard for HMT at 10:40 am you can see we have the data that was taken at initial start up is showing but the messages for successful time update or talked to nodes is not present. I know that there were errors while trying to send that data because I was connected with kip on his tablet.

**Comment by alondrathompson** [comment]
I'm not completely sure what's causing this issue, but I wonder if part of the problem can be attributed to heat and the fact that the gateway is using a 2G network. 

Heat messes with radio signals, and I saw that the box temperatures have been in excess of 90F recently. The battery voltages look ok, but the charging circuit does cut off above a certain temperature but I don't know the exact number. 

2G networks are less reliable than 3G or 4G, which we've seen in the past. 

We may not be able to completely fix this issue. If resetting the system seems to work in at least getting the data to Hologram, that may be the way to handle this as annoying as that is.

**Comment by elhenriq** [comment]
Kip went back today to check on this farm and raise the nodes. so far, the gateway is still connecting to a 2G network, but it seems to be able to send the data now. will keep an eye on it.

**Comment by elhenriq** [comment]
everything is good on this farm
