### ISSUE TITLE
New tablet sleep mode setting

### ISSUE THREAD

**Issue by annabirnbaum** [precision-sustainable-ag/On-farm-Protocols#21]
Trying out the "contact IT" button on new tablet...
The tablet comes out of sleep mode and opens up the home screen with the slightest touch of the touch screen (picking it up. moving around in backpack etc) resulting in fast battery drain.  I don't believe I have access to adjust this is settings.

**Comment by annabirnbaum** [comment]
Why can't we use the camera on the new tablet?

**Comment by saseehav** [comment]
I will add the camera to your tablet. we are just learning the settings that we need to turn on. 
Having trouble with the lock screen still. I will test it out now
