### ISSUE TITLE
Water Sensors- BRW MO

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#210]
This site has been down since 07/03/2022. Was recording pretty consistently with a few gaps in life. Low signal strength all around with nodes and gateway. Reset?

**Comment by ethansweep** [comment]
Sent this to Charles:

This field site has not connected to the tech dashboard in quite some time
Print off the logs for this field from the nodes and gateway and email them to Ethan
Try resetting the nodes and gateway to see if that resolves the issue
