### ISSUE TITLE
Water Sensors- CUU MD

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#211]
This site has been on and off throughout life with numerous resets. Currently offline. Went offline on 06/28/2022. Fairly low signal strength. 

Any updates on this site?

**Comment by ethansweep** [comment]
@kldriver This site has had some spotty service throughout the years we've done it here, but the nodes and gateway are logging the data.
Alondra will be getting us a new 4G card to install on this site within the week. Perhaps that'll solve the issue.

**Comment by ethansweep** [comment]
A new gateway with a 4G SIM card was installed at this site yesterday (7/19/22). The gateway communicated with the dashboard when changed out and the data came through when it was replaced. The data was printed from the nodes and gateway and will be uploaded to the Google Drive.

Interestingly, at 12:00 pm on 07/20/22, the tech dashboard is saying that the gateway was, "Active within the last 4 hours," but that the "Last session: 2 hours ago". The most recent string to come through was: 

{"new_imei": "865456055983900", "prev_imei": "014682005382139", "msg": "Device 1724908 IMEI change from 014682005382139 to 865456055983900"} | Wednesday, May 18th 2022, 2:37:58 PM

Note the timestamp on this string. This message seems to be popping up more frequently. 
-- | --
