### ISSUE TITLE
Water Sensors- DGF FL

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#213]
Went offline on 07/11/2022. Low signal strength with the last transmission. Only been a few days, so not an emergency but needs attention.

**Comment by elhenriq** [comment]
Contacted Danielle to check and download data on this farm.

**Comment by elhenriq** [comment]
Cover crop node 1 has a sensor that is addressed as "p" instead of "a". this makes the data not show up on the graphs. next time they will go to the field, they will update this address and download the data.

**Comment by elhenriq** [comment]
they visited the site. and were able to change the address back to "a". cover one has a sensors sending data since 6-11 to 8-2 that is name "p" and the data should be fix to correspond to a. node barcode is 18000537

**Comment by elhenriq** [comment]
talking today in the hotline meeting, it came up that having a short on the temperature sensor can create the nodes to replace the address on a specific sensor (TDR) will have to investigate some more into this.

**Comment by kldriver** [comment]
@elhenriq Did anything come from further inspection?

**Comment by elhenriq** [comment]
data was saved in google drive. probably will update soon

**Comment by saseehav** [comment]
This site is offline with periodic data collections.
