### ISSUE TITLE
Water Sensors- DWV MO

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#215]
SIte went offline 07/02/2022. Successfully recorded data before that point. Moderately low signal strength recorded at last transmission. It's been over a week so this needs emergency attention. If it has already been attended to, please record updates.

**Comment by ethansweep** [comment]
Sent to Charles:

This site has not communicated with the tech dashboard in quite some time

Print off the logs for this field from the nodes and gateway and email them to Ethan

Try resetting the nodes and gateway to see if that resolves the issue

The 10cm sensor connected to node #18000617 is showing -999 which means that there is some kind of error 
- Pull the sensor out of the ground and check if the tines are bent in any way
