### ISSUE TITLE
Water Sensors- EBT MO

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#217]
This site made a connection and sent a single reading at 8:45 am on 06/07/2022 sending a ~999 and then sent no more readings. Do we know what is happening at this site?

**Comment by ethansweep** [comment]
Sent to Charles:

This site has not communicated to the tech dashboard in quite some time
- It came back online briefly after a reset on 06/30/22 then went down almost immediately after 

Print off the logs for this field from the nodes and gateway and email them to Ethan

Try resetting the nodes and gateway to see if that resolves the issue

The surface sensor and 75cm sensor depth connected to node #18000504 are showing -999 which means there is some kind of error
- Pull these sensors out of the ground and check if the tines are bent in anyway

**Comment by kldriver** [comment]
Any status updates for this site?
