### ISSUE TITLE
Water Sensors- ECP Indigo

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#218]
Rep 1 at this site never made an initial connection. Do Ryan or the tech for this site know what is going on there? Rep 2 struggled to make an initial connection but has since connected as of 07/12/2022. Do we know why 2 was successful after the apparent reset while 1 was not?

**Comment by ethansweep** [comment]
I emailed Ryan about this issue on July 12 with the following issues and recommendations: 

System never made initial contact with the dashboard
- Make sure that the gateway and nodes are all turned on
- Plug into the nodes and gateway to see if the collected any data while it’s been installed

Reset the whole system

Add farm code to the tech dashboard

**Comment by ethansweep** [comment]
Nodes #18000635 and #18000636 are not appearing in the chart view. Data was coming in on device status on August 17.
@brianwdavis @mikahpinegar
