### ISSUE TITLE
Missing Submitted farm history Kobo form

### ISSUE THREAD

**Issue by annabirnbaum** [precision-sustainable-ag/On-farm-Protocols#22]
I submitted a psa_farm_history kobo form for farmer Lee Nunn on 1/15/2021 using one of the old tablets that I have since mailed back to NCSU. I went to Kobo on my desktop to see if I could view the information in the submitted form for Lee Nunn.  I can only see data for forms I submitted after Feb 1 when the last update to the form was made.  I want to make sure that the Lee Nunn data is somewhere and that I do not need to re-interview the farmer. Is there a way I can view this submitted form without the old tablet?

**Comment by saseehav** [comment]
I see 3 forms submitted for GA - Gaines, Gasset and Anderson. 
I can open the old tablet and see if it is saved in the kobo server there.
