### ISSUE TITLE
Water Sensors- FLZ NC

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#220]
Site is Semi-Online. Site was completely offline between 06/16/2022 with all four nodes down until 07/12 when Rep 1 Cover came back online. Rep 1 Bare and rep 2 remain offline. How did we get rep 1 Cover back? Can the same be done for the other nodes? Are we collecting and storing the data that isn't being sent?

**Comment by AlstonBetts** [comment]
Will investigate in the field ASAP and print data from the missing nodes
