### ISSUE TITLE
Water Sensors- HBU IN

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#222]
Site went completely offline 07/10/2022. Last transmission shows very poor cellular connection for two of the nodes and poor for the others. Can this site be reconnected?  Do we know if this site is still printing data? Hasn't been offline long, may come back on it's own. If longer than a few more days ie 07/18 definitely warrants attention.

**Comment by ethansweep** [comment]
Sent to Purdue On-Farm team members from PSA Team Member spreadsheet:

This site has not communicated with the tech dashboard in a couple of weeks

Print off the logs for this field from the nodes and gateway and email them to Ethan

Try resetting the nodes and gateway to see if that resolves the issue

**Comment by kldriver** [comment]
This site is communicating and showing up in device status but isn't showing up in chart view. @brianwdavis @mikahpinegar do we know why this is?
