### ISSUE TITLE
Water Sensors- JKB Indigo

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#225]
Site JKB went down completely 07/12/2022 at 10am. Last transmission shows poor signal strength. Can we reset? Do we have data collection in the meantime?

**Comment by ethansweep** [comment]
Emailed Ryan about this on 12 July with the recommendation to check the to see that the data has been logged, and to reset the system.

**Comment by kldriver** [comment]
Do we have a status update on this site?

**Comment by ethansweep** [comment]
Rep 1 sensors are sending data to the tech dashboard, but are not filling in the chart view 
@brianwdavis @mikahpinegar
