### ISSUE TITLE
Water Sensors- NMO FL

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#227]
SIte went fully offline 06/17/2022. Successfully logged 3 days from all nodes then went offline. Do we know if this site has received attention? Is this site collecting data and reconnecting when it can aka just fine, does this site need to go in receiver only mode, or is something more going on?

**Comment by elhenriq** [comment]
Contacted Danielle to check and download data on this farm.

**Comment by elhenriq** [comment]
this farm has been moved to receiver mode. this farm has been talking to a 2G tower and cant send the data. all data has been downloaded from the nodes and will move to the drive. additionally, this farm had two sensors with broken cables in the cover 1. the cables have been chewed. middle sensors was able to fix but need to send a new temperature sensor.
