### ISSUE TITLE
Water Sensors- QAQ NE

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#228]
Never made initial connection (presumably).  Unlisted.

**Comment by elhenriq** [comment]
Contacted Tauana to check what is going on with this farm and asked to download data from it.

**Comment by kldriver** [comment]
I did not see a successful upload of downloaded data from this site's gateway or nodes in the drive folder. Do we have a status update for this site?

**Comment by AlstonBetts** [comment]
I see data from June 9 - July 3 on the chart view. Had to change the name in device status to find the data there. I asked Andrea to go download data from the nodes and gateway and email the files.

**Comment by elhenriq** [comment]
was going over the data that has been submitted into the folder,
 Bare 2 for shallow and middle sensors is reading as -999.

**Comment by elhenriq** [comment]
data was downloaded from them. Tauana sent me only data for one node. asked her for the rest of it for the other nodes. data looks complete

**Comment by elhenriq** [comment]
received the reset of the data now. Cover 1 had an error happened and lost date it says is 2060 right now. not sure what to do. @brianwdavis any guess? file name is QAQ.Cover1.serial_20220804_154802


Bare 2 has probles with shallow and middle sensors, reading as -999

**Comment by elhenriq** [comment]
for Bare 2 it looks like the farmer drove over the sensors and broke them. not sure if we should send replacements. i think we are past the threshold for data collection.
