### ISSUE TITLE
Water Sensors- QNE VA W

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#229]
Sending something as of 07/15/2022. Was completely offline for a long time after 6/16.  Still not listed as online. some ~999 transmissions 07/15

**Comment by ethansweep** [comment]
@brianwdavis @elhenriq  in the "chart view" for this field there are three graphs that have surface sensors showing up (Rep 1 Bare, Rep 1 Cover, and Rep 2 Bare). There shouldn't be a surface sensor coming from a Bare 2 plot, and it only showed up after 06/04/22.

**Comment by ethansweep** [comment]
Sent Cynthia the following:

The surface sensor on one of the Rep 1 nodes isn’t sending any data
- Most likely the Rep 1 Bare node
- Check to see if this sensor is connected to the junction box correctly, and there is no visible damage to any of the cords

The 40cm sensor depth connected to node #18000638 is showing a string of -999 which means there is some kind of error
- Pull the sensor out of the ground and check if the tines are bent in any way
- You will probably need a post puller for this

Print off the logs for this field from the nodes and gateway and email them to Ethan 

While plugged into the gateway, set it to “Receiver Mode”

The chart view isn’t showing any data after the new node at this field was installed and the reinstallation form was submitted
- Go onto the tech dashboard ([onfarmtech.org](http://onfarmtech.org/)) and located the forms that you have submitted
- Go to the “Please Fix” tab and correct any errors made in submitting the form

**Comment by elhenriq** [comment]
@brianwdavis @mikahpinegar can you check on this farm, we see that data is coming in from two of the nodes but no data is being graph onto chart view.

**Comment by saseehav** [comment]
currently the working theory is that after receiving their new node, they installed the new hardware but did not fill out a new sensor install form. Sarah reached out to Cynthia on 8/11
