### ISSUE TITLE
Water Sensors- RCS Indigo

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#230]
Been completely offline since 07/13/2022. Rep 1 and 2 bare have been offline since 07/04/2022. Seems there was a reset on 07/12 or 07/13 but it was only somewhat successful. What more can we do?

**Comment by ethansweep** [comment]
Here's the issues and solutions I sent to Ryan on 12 July: 
Sensors were last active 8 days ago and will need to be reset

Node #18001810 is getting a -999 from the 70cm sensor depth
- Remove the sensor and check to see if the tines are bent in any way

Bare 1 - surface sensor never made the initial connection
- Check the wiring and see if everything is connected, or if anything is damaged

Gateway is only connected to three nodes (18001852, 18001850, and 18001810) 
- Check to see that the fourth node is turned on and everything is connected

Reset the system

I will take another look at this on the dashboard and see if there's anything more we can try than just a reset.

**Comment by ethansweep** [comment]
Sent Ryan another email about this site today (07/22)

**Comment by elhenriq** [comment]
Ronaldo called today. he is downloading data from the gateway but only shows data up to july 20th. he will download data from all nodes and set gateway to receiver mode.

**Comment by ethansweep** [comment]
Node #18001810 has -999 for all the depths on the sensors so they are not appearing in chart view
@brianwdavis @mikahpinegar
