### ISSUE TITLE
Water Sensors- REK IN

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#231]
Site has been offline for over a month since 06/22/2022 at 7 am. Is this site "just fine" and logging data just not sending it or does it need emergency attention? Please let me know so I can denote in summary.

**Comment by ethansweep** [comment]
Sent to the Purdue On-Farm team members:

This site has not communicated with the tech dashboard in quite some time

Print off the logs for this field from the nodes and gateway and email them to Ethan 

Try resetting the nodes and gateway to see if that resolves the issue

**Comment by kldriver** [comment]
Do we have a status update for this site that has been offline for 20 days?

**Comment by ethansweep** [comment]
They reached out to me on August 5 with the downloaded data off of the nodes from this site. They noted that this gateway was turned off and they were unable to turn it back on. They plan on downloading data every couple of weeks. 
I put the files they emailed me into Google Drive
