### ISSUE TITLE
Water Sensors- SOW VA W

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#233]
Site never made initial connection.

**Comment by saseehav** [comment]
Sarah emailed Cynthia 8/11 to ask about last check at this site. Cynthia responded that Esleyther had helped her take this site offline since it was never able to have cell signal. No files uploaded for this site yet.

**Comment by ethansweep** [comment]
Cynthia is downloading the data from the nodes today. When she was connected to the gateway she noticed there was an "SD error" message popping up. Upon further inspection, Cynthia noticed that the SD card is cracked and when she tried to take it out it wouldn't budge.

**Comment by elhenriq** [comment]
I checked over the data that was uploaded for this farm, Bare 2 was not reading any of the sensors, so no data is present on the node. (the node was on, but no sensors were detected).  Cover 2 and Cover 1 are perfectly good. 

there is no file for Bare 1 they submitted a gateway file for ULW as Bare 1 SOW
