### ISSUE TITLE
Water Sensors- SVC  PFI

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#234]
Site went completely offline 07/11/2022. Last transmission showed low signal strength after a decline for most nodes. Is this site printing data and simply unable to connect or does it need emergency attention? Comment feedback and/or updates below.

**Comment by AlstonBetts** [comment]
Having Stephan reset

**Comment by kldriver** [comment]
This site is back online and has been effectively collecting and sending data since 08/16/2022. Do we have data that we can print and upload for the month-long gap between mid-July to mid-August while it was offline? @AlstonBetts

**Comment by AlstonBetts** [comment]
Another where tablet wasn't saving download data. Should have the files this week.
