### ISSUE TITLE
Water Sensors- VEZ VA W

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#235]
Site awoke 05/19/2022 and sent one data point then never reconnected. Is this site printing data and just not sending it? Has this site received attention? Does it need emergency attention? Comment feedback and/or updates below.

**Comment by ethansweep** [comment]
Sent Cynthia the following:

This field site connected to the dashboard briefly, but only sent a handful of data strings
- After that it would only send the same strings of data over and over again
- Gateway is connected to nodes #18000617, #18000554, and #18000538
- Find the fourth node that is not one of these three and make sure that it is turned on and working correctly
- Mostly like the Rep 1 Cover

The 75cm depth connected to node #18000617 (Rep 2 Cover(?)) is showing a string of -999 which means there is some kind of error
- Pull the sensor out of the ground and check if the tines are bent in any way
- You will need a post puller for this

Print off the logs for this field from the nodes and gateway and email them to Ethan 

While plugged into the gateway set it to “Receiver Mode”
