### ISSUE TITLE
Water Sensors- VZC MD

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#236]
Site went completely offline 06/23/2022. Sucessfully logged data previously. Is this site printing data and just not connecting to the cellular network? Has this site received attention? Does this site need urgent attention? Comment feedback and/or updates below.

**Comment by ethansweep** [comment]
Sent Ethan the following:

This site has not communicated with the dashboard in a while

Gateway is only connected to nodes #18000383, #18000478, and #18000353
- Check to see that the other node is turned on and everything is connected

Print off the logs for this field from the nodes and gateway and email them to Ethan

Try resetting the nodes and gateway to see if that resolves the issue
