### ISSUE TITLE
Water Sensors- WBS Indigo

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#237]
Rep 1 Cover never made the initial connection. Do we know if this node is printing data? Rep 2 Cover went offline 07/02/2022. Rep 1 and 2 Bare went completely offline on 07/13/2022. Device status shows data from 2 nodes 07/18/2022, one Rep 1 and one Rep 2 but this is not reflected in the chart view on the tech dashboard. Do we know if this site has the data from the meantime between 07/02 and present-day as well as 07/13 and present-day for the sensors to which it applies? Please update what we know below.

**Comment by ethansweep** [comment]
Sent Ryan the following:

Gateway is only connected to nodes #18001812 and #18001833

Check to see that the other two nodes are turned on and everything is connected

Print off the logs for this field from the nodes and gateway and email them to Ethan 

Try resetting the nodes and gateway to see if that resolves the issue

**Comment by ethansweep** [comment]
The node for BT-1 is not connecting to the gateway for some reason. It's allocated to the correct gateway in the field. 
Instructed Bryan (tech for this site) to leave it alone and that he'll have to come back every so often and manually download the data.
