### ISSUE TITLE
Water Sensors- XVB VA W

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#239]
This site went completely offline 07/02/2022 with all nodes stopping connection at the same time. This site appears to have been reset 06/29/2022 as there is a gap between 06/13/2022 and 06/29/2022. This site successfully transmitted data initially, went offline between 06/13 and 06/29 where there is a gap on the tech dashboard, do we know that this data exists? Has there been data collection since the site went offline 07/02? The signal strength for all nodes is less than -68 at last transmission. Updates below, please.

**Comment by ethansweep** [comment]
Sent Cynthia the following:

This field site has not connected to the tech dashboard in quite some time
- The gateway stopped communicating with the dashboard before being reset, coming online, then going back down again

Print off the logs for this field from the nodes and gateway and email them to Ethan 

Try resetting the nodes and gateway again to see if that resolves the issue

The signal strength for this site is really low, so it may not be able to connect and you’ll have to manually download the data occasionally

If necessary, while plugged into the gateway set it to “Receiver Mode”

**Comment by ethansweep** [comment]
Kevin Bamber from VA Tech checked on this site today as well. He performed a reset of the system, and when I checked it on the dashboard the gateway was sending strings of data from each node.
