### ISSUE TITLE
Water Sensors- YBR WI

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#240]
Sensor awake 04/20/2022 and successfully sent data for three nodes a few different times that day. After which the gateway sent successful time updates intermittently until 05/26/2022 when the gateway sent.

{"new_imei": "014682005381974", "prev_imei": "014201000957520", "msg": "Device 293874 IMEI change from 014201000957520 to 014682005381974"}

Tech: Do you know what this means? Has this site received attention since 05/26/2022? Is this site printing data? Update below, please.

**Comment by ethansweep** [comment]
Emailed Ashley the following:

Nodes never made initial connection with the gateway

Check to see that all the nodes and gateway are turned on and everything is properly connected

Print off the logs for this field from the nodes and gateway and email them to Ethan

Try resetting the nodes and gateway to see if that resolves the issue

**Comment by ethansweep** [comment]
Received a message back from Ashley that they will be out at YBR in about 2 weeks.

**Comment by kldriver** [comment]
Any update from this week or last as it has been 23 days?
