### ISSUE TITLE
Water Sensors- ZSB Indigo

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#241]
Rep 1 Cover, Rep 2 came online 06/08/2022 and successfully logged data for 9 days going completely offline 06/16/2022. Rep 1 Bare never made initial connection. Do we know if this site has been printing data in the meantime? The last signal strength indicated wasy less than -75 for all components. Is this a site that is just fine not connecting but collecting data offline? Update below, please.

**Comment by ethansweep** [comment]
Sent Ryan the following issues and solutions on 12 July: 

Gateway is only connected to three nodes (18000655, 18000665, and 18000632) 
- Check and see that the fourth node is turned on and everything is connected
- Reset the system

**Comment by ethansweep** [comment]
Rep 1 Bare node is not showing up in the chart view. There's also no node serial number listed on the chart view for this treatment. The form has been submitted and there are no issues to correct. The form has all four node serial numbers in it. 
@brianwdavis @mikahpinegar
