### ISSUE TITLE
Water Sensors- DBS SC

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#242]
This site went completely offline on 07/14/2022. Successfully logged and sent data before. May need attention. 

Last signal strength: less than -66 for all components. 

Do we know that it is collecting? Will it reconnect when it can? 

Update below, please.

**Comment by elhenriq** [comment]
contacted Payton and requested to check on the water sensors.

**Comment by kldriver** [comment]
This site has been off again for 5 days. Is it a signal strength issue? is it collecting data?

**Comment by elhenriq** [comment]
data has been download and saved on the google drive
