### ISSUE TITLE
Water Sensors- VQQ MD

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#245]
Site went completely offline 07/13/2022. Was successfully logging and sending. 

Does this site need a reset? Is there bad cellular reception? 

Is this site printing? Can it be classified as Just Fine?

**Comment by ethansweep** [comment]
This gateway at this site was switched out for a gateway with a 4G SIM card from Alondra this morning (07/20/22). The tech dashboard is showing communication from the gateway, but it has only sent two strings which were both successful time stamp updates.

**Comment by saseehav** [comment]
<img width="884" alt="image" src="https://user-images.githubusercontent.com/49722541/180284622-03bd46bc-0613-48fe-8a14-561339c17ddf.png">
Also - interesting odd timestamp on the tech dashboard from May from a Gateway startup message @brianwdavis  also in CUU Issue #211

**Comment by kldriver** [comment]
Site came fully back online then went back off 08/05/2022. Shouldn't be a signal issue as it has a gateway with a 4G SIM card.
