### ISSUE TITLE
Water sensors MLN

### ISSUE THREAD

**Issue by elhenriq** [precision-sustainable-ag/On-farm-Protocols#246]
this farm in AL is having intermittent connection, sometimes it comes on and sends the data, but it might take multiple hours to do that. I believe this is related to issue #209. additionally, when I look at the graphs for this farm the data says the last string is from July 13th but when I look at the device view I see data from the 20th. are we having issues on the backend?

**Comment by saseehav** [comment]
@mikahpinegar see issue #249 also - for graphs only visualize data up to a certain date. Not graphing most current data string.

**Comment by mikahpinegar** [comment]
this should be fixed now

**Comment by elhenriq** [comment]
@kldriver this farm was moved to manual data collection today. it stops communicating 6 days ago and kip went back to check on them, i connected to his tablet and check for connection. this farm stop getting 3G network signal and is only talking to a 2G network. there is nothing we can do to change that at the moment. 

he will go back in a couple of weeks to download the data from them.
