### ISSUE TITLE
Water sensors- FLI Indigo

### ISSUE THREAD

**Issue by elhenriq** [precision-sustainable-ag/On-farm-Protocols#249]
no data coming in since installed. this farm was installed on July 7th. i asked him to go and check all the devices for water data on them. and record the information to send back to us.

**Comment by elhenriq** [comment]
Brian called today about this farm. he is downloading data from all the nodes, they seem to be working fine, but we don't know since his farm wasn't graphing. there is an error with his form, for some reason his the dashboard thinks that the form was submitted for a 2021 farm instead of this year, @brianwdavis or @mikahpinegar  any clues on what is going on here?

he also has to check on B1 the middle sensor is reading 999. one of the prongs was bent. he fixed it and placed back in the ground. it is reading correctly now. 

C2 was not connecting to the gateway, he will download the data from the node to make sure it is complete.

**Comment by mikahpinegar** [comment]
oh weird, the form was started `"today": "2021-09-28",` but submitted `"_submission_time": "2022-07-07T17:01:43"`

**Comment by mikahpinegar** [comment]
we currently use the `today` field instead of `_submission_time` to determine when a form was submitted, so it thinks this form is a 2021 form

**Comment by elhenriq** [comment]
this farm is from this year 2022 it was install a few weeks ago.

**Comment by saseehav** [comment]
@mikahpinegar what's the reason that you use the "today" field and not the "submission time " field or "date installed" field instead?

**Comment by elhenriq** [comment]
also the "today" date was july 7th so it should have picked up as 2022 anyways

**Comment by mikahpinegar** [comment]
ah i got confused. we actually use `end` to check the year of a form which in this case is `"end": "2021-09-28T06:44:13.152-04:00"`. we can't use `date_installed` because it's not on every form. we have to use a field that is inseerted by kobo and present on all forms

**Comment by mikahpinegar** [comment]
we could switch to `_submission_time`. i think me and brian used `end` because we thought it was when the form was finished being filled out, so if the farmer didn't submit the form for a month or whatever and that happened to be in the next year we would still be able to tell the correct year

**Comment by elhenriq** [comment]
how can we change this particular form so it can get parse and his data can show?

**Comment by mikahpinegar** [comment]
i can do it manually

**Comment by mikahpinegar** [comment]
i resubmitted the form and copied `submission_time` into `end` it should show up in 5 mins or so

**Comment by mikahpinegar** [comment]
it's showing up as valid now

**Comment by elhenriq** [comment]
UPDATE ON DATA 

he was able to collect all the data from all the nodes, and they all seem to be working fine. we were able to get the gateway going sending and receiving all data now

**Comment by saseehav** [comment]
Surface sensor in Bare rep 1 is reading 0% VWV. who is contacting to do a re-install? fix?

**Comment by elhenriq** [comment]
im with him on the phone right now, i just saw that and asked him to go and take a look. might need a replacement.

**Comment by screberg** [comment]
Surface center was never installed.  Installing it today

**Comment by elhenriq** [comment]
@mikahpinegar i see the graph have populated now. but i only see data up to a certain date, but i know for a fact that there is data from today that is showing on the device status page for this farm. any guess on what is going on there?

**Comment by saseehav** [comment]
@mikahpinegar noticed in audit log that at 13:20 FLI was updated in the Farm History table. Could this have been you instead of updating the water sensor install time end?

**Comment by mikahpinegar** [comment]
the install forms update `cash_crop_planting_date` in farm_history so when i manually edited the form and it passed through it also updated farm_history

**Comment by mikahpinegar** [comment]
as for the graphs showing old data, it's getting returned from the api that way. i'm not super familiar with the soil moisture api so i'll let rick and brian know what's going on and also poke around myself

**Comment by mikahpinegar** [comment]
did the sites that aren't showing new data have sensors swapped at any point?

**Comment by mikahpinegar** [comment]
ok @brianwdavis fixed the issue and all the sensor graphs should be up to date now

**Comment by elhenriq** [comment]
Awesome, i just checked and all data is there.

**Comment by kldriver** [comment]
Rep 2 Bare (625) is completely offline, Is this a wire connection issue?

**Comment by elhenriq** [comment]
checked with brian and ask to download data from it.
