### ISSUE TITLE
Water sensors ZZN  Indigo

### ISSUE THREAD

**Issue by elhenriq** [precision-sustainable-ag/On-farm-Protocols#250]
no data coming in since installed. this farm was installed on June 15th. i asked him to go and check all the devices for water data on them. and record the information to send back to us.

**Comment by elhenriq** [comment]
Brian called back today, and we were able to download all the data from each node since the moment of install. B1 has two sensors that are not working properly, we tried to troubleshoot them, but they will need to be replaced. I'm sending him the replacements. 

the gateway on this farm did not collect data since the moment of install, but as of right now it is connected to the nodes and the network. and working fine.

**Comment by kldriver** [comment]
Rep 1 Cover offline. Other nodes transmitting. 1C went offline since 08/02/2022

**Comment by elhenriq** [comment]
Contacted Brian to take a look at that farm
