### ISSUE TITLE
Water Sensors: CRK SC

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#254]
This site went completely offline on 07/16/2022. Has this site been attended to or reset? Do we have the data that hasn't been pushed to the dashboard, provided data is being collected?

**Comment by elhenriq** [comment]
Contacted Payton today, email attach

Hello Payton, just wanted to check with you on farm CRK we notice it has come down and is not transmitting data anymore. can you go and check on this farm? when you do, can you download the data manually from the nodes. I want to see how they are doing and maybe fill out the missing data on the graph. 

thanks a lot.

**Comment by kldriver** [comment]
This site is semi-online. Bare 1 and 2 are online while cover 1 and 2 are not. Can we follow up with Payton?

**Comment by kldriver** [comment]
This site is now fully offline. Is there something more we can have Payton do @elhenriq ?

**Comment by elhenriq** [comment]
this farm  is up and running right now. data has been loaded into the google drive.
