### ISSUE TITLE
Water Sensors: HMI PFI

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#255]
This site went completely offline on 07/17/2022. Alston reached out to Stephan to reset 07/25/2022. Not showing in the dashboard as of 4 pm 07/26/2022. Update below.

**Comment by kldriver** [comment]
This site is offline again as of 08/11/2022. The last satellite signal readings are around the -90s. Do we need to reset again? Is this site collecting data even though it isn't connecting? @AlstonBetts

**Comment by AlstonBetts** [comment]
I couldn't find any downloaded data to confirm the nodes are still taking data, but they should be. I'm going to have them go out and reset/check on the nodes.

**Comment by AlstonBetts** [comment]
He is going out to download data from all sites this week. They were one where the tablet wasn't saving data downloads, but that issue was fixed.
