### ISSUE TITLE
Water Sensors: DET VT

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#267]
This site went down 08/03/2022. Has been offline for 5 days now. Has had some data printing and noisy data issues in the past. Please reach out to Ashley to check on sensors.

**Comment by saseehav** [comment]
Put in receiver mode 8/16 and Lindsey downloaded all her files. Ethan has the files emailed to him

**Comment by saseehav** [comment]
Middle Rep 2 Cover Sensor has periodic jumps to 0% VWC at random intervals.
Chris bets that it is not fully inserted. 
Sarah wagers that the prong is bent. 12 donuts are on the line. Also Ethan.
Alston bets a rock.
