### ISSUE TITLE
Water Sensors: VWD VA E

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#268]
This site went down 08/03/2022. After a brief stint online from 08/01/2022 to 8/03/2022. Is this an issue of signal strength?

**Comment by kldriver** [comment]
Sitw went completely offline on 08/19/2022 after recovering from the outage on 08/03/2022. @elhenriq can you give insight as to why this may be recurring?

**Comment by elhenriq** [comment]
Contacted Joey for info on this farm
