### ISSUE TITLE
Water Sensors: ERU

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#269]
The site has been offline for over a month. Unconfirmed connection with issue #202. Can we clarify what is/was going on with this site?

**Comment by elhenriq** [comment]
i was going over the data that was downloaded for this farm. i notice all of the sensors were not reading for Cover 1 when they downloaded on 08/06. should send back to check on it.

**Comment by AlstonBetts** [comment]
Letting them know to check on Cover 1
