### ISSUE TITLE
Water Sensors: DRK PFI

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#276]
This site is partially offline. Only 830 and 819 are transmitting. Do we know if the other nodes are collecting data and just not making a connection? Can someone get out there and check connections? Do we need to reset it?

**Comment by AlstonBetts** [comment]
I'm having them go out to download data off those two nodes and reset the entire set. Batteries are good, and connectivity has been a bit messy with those two nodes so I think they just stopped talking to gateway.

**Comment by elhenriq** [comment]
refer to issue #282
