### ISSUE TITLE
Indigo ag-Jake Linneman

### ISSUE THREAD

**Issue by elhenriq** [precision-sustainable-ag/On-farm-Protocols#287]
he uninstalled the water sensors for ECP and ZSB and downloaded the node data, he was trying to send me that info, but his tablet was not responding on Gmail or Google Drive. I ended up just asking to keep that with him since he is sending nodes and gateway to us. 

he also mentioned that he never uploaded the videos for weeds3D, I tried loading them with him but couldn't, when downloading them it would give an error (not able to download video). I gave him the W3D hotline number for him to get more info from Zack.

**Comment by saseehav** [comment]
@brianwdavis let's check the last upload of the manual downloaded files for the water sensors. ECP files have rep 2 complete-ish but not rep 1. Manually input the repeated node serial numbers. ECP rep1 is a repeated serial number.

**Comment by saseehav** [comment]
Find out if Jake Linneman still has a tablet or if Ryan has it.
