### ISSUE TITLE
Gateway SD shipping damage

### ISSUE THREAD

**Issue by AlstonBetts** [precision-sustainable-ag/On-farm-Protocols#288]
I've run across two gateways now that have cracked SD cards from transport. They were shipped with the PVC adaptor inside, I think they are bumping the SD and breaking them. 
![image](https://user-images.githubusercontent.com/75508399/199572277-aebf703d-1b6e-49be-8e15-670a31e2f377.jpeg)
![image](https://user-images.githubusercontent.com/75508399/199572407-7c91696b-b7cc-407d-bdba-1ce998dbe052.jpeg)
![image](https://user-images.githubusercontent.com/75508399/199572474-a6c70ad2-c0f9-4f30-96df-850fa8b7cc6e.jpeg)
![image](https://user-images.githubusercontent.com/75508399/199572514-fb26a384-29cd-464f-849c-5ca59db5b2b6.jpeg)
Two gateways with bad SDs (so far) are
MN 293875 (134)
KS 164670 (166)

**Comment by saseehav** [comment]
Alston replaced these sd cards with new ones. Unclear on data lost. We took data from the nodes off and saved it. Unable to retrive data from these cracked sd cards. Only 2 found in 2022.
