### ISSUE TITLE
Geoscout turning off/power cord issue- Akwasi at Purdue

### ISSUE THREAD

**Issue by jordannicolette** [precision-sustainable-ag/On-farm-Protocols#294]
**What's wrong**
Geoscout not holding power after turning on and shutting off. User has charged his battery overnight and the charger gives him a green light, but when he plugs the battery into the power cable and the geoscout, the geoscout won't stay on and will shut off. The user says his power cable is intact, but the battery charger's connection to the battery is loose. 

I suggested finding a voltmeter to test if the battery isn't actually charged. The user may need a new power cable, but will be getting a voltometer from a colleague soon to test battery's power. They were able to collect data before with no issues. 

https://user-images.githubusercontent.com/114753859/230480421-357c0732-a015-4a32-b855-949022cdd6d6.mov

**Comment by jordannicolette** [comment]
Update 4/7:
Users have acquired a voltmeter and tested the battery, which is at a full charge. They noted that their sensor is not showing any light still, most likely because power can't be taken from the battery to the geoscout. They are trying to scan next week. I believe they have a faulty powercord and if we have any extras if we could send one to Purdue ASAP @elhenriq @kldriver

**Comment by saseehav** [comment]
fuse replacement fixed issue (also see issue #293 )
