### ISSUE TITLE
HS Sensor 2 No Report/faulty sensor - Charles Ellis UMO

### ISSUE THREAD

**Issue by jordannicolette** [precision-sustainable-ag/On-farm-Protocols#296]
**What's wrong**
Geoscout reads HS sensor 2 screen as no report - despite sensor lights turning on and full internal and external voltage.

User called Josh Pittman since I missed their original call. Josh diagnosed the issue as a faulty sensor and is overnight shipping the sensor to josh for a repair. This is the users first time using the sensor this season.

Will update this thread with an update from josh when he ships it back. Not sure when the user plans to terminate cover crops

**Comment by saseehav** [comment]
@jordannicolette status on sensor repair for this site?

**Comment by jordannicolette** [comment]
I'll follow up with Josh/Charles

**Comment by jordannicolette** [comment]
@saseehav Geoscout is still with Josh for repairs. He had to get a few special parts from Kyle. At this point should he send it back to us once its repaired? Even if he sent it back to the user for corn scans, the corn may be too tall

**Comment by jordannicolette** [comment]
Talked with Josh Pittman who gave me a detailed explanation about the bug on this device and how it's still persisting. The geoscout will be sent to Kyle for its final repairs. The ID on the unit is 272907. Josh also mentioned to be sure to keep this devices cables with the unit and not to swap them with other cables.
