### ISSUE TITLE
Geoscout not holding power- Rashelle  Matthiesen Iowa

### ISSUE THREAD

**Issue by jordannicolette** [precision-sustainable-ag/On-farm-Protocols#297]
After talking with Rashelle we've concluded there is a short somewhere in her geoscout. It is reading that it's getting no external voltage, but her team used a voltmeter and tested the voltage of the battery and the tip of the power cord, both reading 13 volts. They have checked for shorts in the power cord and none are found. I have contacted Josh to see if they can send the Geoscout to him. They are looking to collect data in another two weeks before termination. Do we have any other geoscouts we could send them in the meantime?

**Comment by saseehav** [comment]
5/3/23.
Rashelle received new Geoscout. still not working. checked the fuses with volt meter, and power is being sent from the battery to the geoscout, and fuses are good.  Maybe needs a new cord? She will continue testing.

**Comment by elhenriq** [comment]
since they tested the cord, I doubt the power cord is the issue, but worth trying, could it be that there is an issue going on with her sensor box? can we send her an entire kit and receive hers back for troubleshooting?

**Comment by kldriver** [comment]
Sending Rachelle the rest of the kit we pulled the geoscout from today.

**Comment by saseehav** [comment]
Rashelle's Geoscout is with Josh

**Comment by jordannicolette** [comment]
Josh sent Rashelle her Geoscout back a few weeks ago. She will be sending back her original repaired and back up Geoscouts and kit this week. She will note which Geoscout was repaired by Josh.
