### ISSUE TITLE
Geoscout screen not turning on despite power

### ISSUE THREAD

**Issue by jordannicolette** [precision-sustainable-ag/On-farm-Protocols#300]
Tauana from Nebraska cannot get her geoscout to power on, despite it receiving charge (see picture). The fuses are intact and battery is fully charged. No lights are turning on on the sensor either. She has tested her forage box before and was able to receive power to her geoscout. 

![image](https://user-images.githubusercontent.com/114753859/234976468-f3618731-71b3-4d81-99a1-29dd070f5f82.jpeg) 
![image](https://user-images.githubusercontent.com/114753859/234979559-07d225b6-0e42-4e01-baef-c245e58f65fb.jpeg)

**Comment by elhenriq** [comment]
I don’t know if this might be the issue but I have had other equipment that uses similar screens have the screen come loose after a drop. 

Also it could be the picture but the screen seem to be burnt

**Comment by jordannicolette** [comment]
Could we send her a new geoscout out today? She's terminating at the end of next week and would like to scan on Wednesday. Sorry to do this on a Friday. @elhenriq @kldriver

**Comment by elhenriq** [comment]
Tracking number 771993920890

**Comment by saseehav** [comment]
Tuana sent Josh the bad Geoscout - he repaired and sent to NC. (?) @kldriver is going to find the serial on the geoscout https://docs.google.com/spreadsheets/d/1Q324qPFwUx0M8V5HTtFrVTVAZ6Ip4CDUwiJZHbOvtb4/edit#gid=0 add more information about tracking and information on the GeoScouts

**Comment by kldriver** [comment]
Geoscout at PSB
