### ISSUE TITLE
Water Sensors: EKG SC

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#303]
**What's wrong**
All nodes are online and functioning. However, R1B deep sensor is reading very close to 0 which is weird. R1C deep sensor appears to be having some issues with choosing a formula (see April 28, May 8).

**What done looks like**
Possibly reinstall R1B so it is not in an air pocket? Not sure what is going on with R1C.

**Comment by kldriver** [comment]
Hello Payton, 
I hope this email finds you well. 

In real-time shepherding the water sensor data at your sites, I noticed a few issues that need attention soon to ensure the quality of your data. 
EKG has all nodes online and functioning, however: 
- Rep 1 Bare is reading very close to 0 which can indicate an air pocket. 
- Rep 1 Cover appears to having some issues with choosing a formula (see chart view 4/28, 5/8). 

Please call Esleyther at the hotline number: (919) 244-‬2749 from the field when you service this site or if you have any questions.

**Comment by elhenriq** [comment]
I will send replacement sensors to Payton! she is using older versions of TDRs for deep cover rep one. sensors a, b, c for rep one cover are also older TDRs. will send replacement for all of them!

**Comment by elhenriq** [comment]
@kldriver any updates on these sensors?

**Comment by kldriver** [comment]
All sensors are transmitting data. R1C middle appears to be struggling to pick a formula, though it clearly favors one.  R2C middle and top are reading the same values which is suspicious. The temp sensor is reading -999. All other numbers look real.

**Comment by elhenriq** [comment]
the letter on the temperature is a lowercase that's why you get -999 on the depth!. as for R1C middle i see what you are saying. i recommend she reinstall it because that is one of the newer sensors and should be working fine. for R2C the reading are close but not the same. still odd though.

**Comment by elhenriq** [comment]
no data, for a while now asking to download again.

**Comment by kldriver** [comment]
Data was downloaded at end of season.
