### ISSUE TITLE
Water Sensors: HAE Indigo

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#306]
**What's wrong**
Rep 2 bare and cover are problematic. 2B never made the initial connection. 2C middle and deep sensors are not transmitting. 

**What done looks like**
Indigo tech go to the site and check the battery and interconnectivity or restart.

**Comment by elhenriq** [comment]
your Rep 2 Bare is not connected to the TDR's most likely just need to reset and reconnect the sensors. simple fix. if encounter problems, call the hotline. on Rep 2 Cover, you are missing the middle sensor. again check for broken cables and make sure there are none, if still not working call hotline.

**Comment by kldriver** [comment]
HAE is online

**Comment by elhenriq** [comment]
received data download from this farm and all good
