### ISSUE TITLE
Water Sensors: LNM Indigo

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#308]
**What's wrong**
A lot of -999 at 11:04 today 5/16. Prior to today, the deep sensor appeared to be missing for R1B and R2C. The middle sensor for R2C also appears to be missing.

**Comment by elhenriq** [comment]
Contacted Brooke for this issue, MY RESPONSE "all of your nodes are connecting in this farm which is good, but I notice that for Bare rep 2, middle and deep sensor are not reading, same thing for middle Bare rep 1.  first thing to troubleshoot is that there are no cable cuts on top of your sensors (check that the PVC cap did not cut the cables at installation). If all your cables are good, another thing to try is pulling the sensors out of the ground, making sure the metal prongs are not bent and touching each other. also in Cover rep 1 your deep sensors are not being read by the node. same thing to check for. cables first".

**Comment by kldriver** [comment]
Site online
