### ISSUE TITLE
Water Sensors: YPH Indigo

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#309]
**What's wrong**
R2C appeared to never make an initial connection but when the gateway woke up it was not noted as missed. All other nodes went offline 5/14.

**Comment by elhenriq** [comment]
Contacted Brooke at indigo and recommended to restart all devices and to please bring her tablet and all cable, so we can troubleshoot the node that never made initial connection.

**Comment by elhenriq** [comment]
received some files from Lee and this is what i noticed

YPH 
Bare rep 1: you only have data until 6-24 the battery at this node had died and stop collecting.
Cover rep 1: data looks good (it will update at the end of the week). 
Bare rep 2: data looks good (it will update at the end of the week).
Cover rep 2: it did not collect data at all. 

the good news is that when you reset everything on 7-10 it started collecting data, and we have good info now.
