### ISSUE TITLE
HVU indigo gateway not working Tyler

### ISSUE THREAD

**Issue by elhenriq** [precision-sustainable-ag/On-farm-Protocols#311]
for some reason, this farms seems to be stuck on a loop of restart. I believe it is due to the battery not being charge all the way and the gateway cant get started. asked Brooke at Indigo to please go to this farm, so we can troubleshoot together.

**Comment by elhenriq** [comment]
Farm was reset and downloaded data, farm is having cellular connectivity issues and gateway cant send all the data all the time. if error persist will move to manual data download. 

gateway has been trying to send data but not enough bandwidth

**Comment by kldriver** [comment]
R1C middle sensor is struggling to choose a formula.

**Comment by kldriver** [comment]
Will poke Tyler today

**Comment by kldriver** [comment]
R2C middle sensor is offline.

**Comment by elhenriq** [comment]
rep 2 cover middle is missing, reading -999 it was replaced recently but went back to -999. rep 1 cover deep is not reading either. check cables and make sure they have not being cut. or cables at junction box have not come loose.

**Comment by kldriver** [comment]
Same issues persist, poking Tyler today

**Comment by elhenriq** [comment]
asked Tyler to download data again from this farm, he sent me some already, but I would like to get it download from the nodes this time.

**Comment by elhenriq** [comment]
data looks good for the most part. cover rep 1 is not collecting data since 7-5 for some reason, only thing I can think of is the memory is corrupted. I will put a new node on the mail later today.

**Comment by elhenriq** [comment]
replaced node in cover rep 1 with 18000674, the old node stopped collecting data for some reason.
