### ISSUE TITLE
sensor install form ZTP from WI

### ISSUE THREAD

**Issue by elhenriq** [precision-sustainable-ag/On-farm-Protocols#315]
when the form submitted the date was set as 2021, but the form is for a farm in 2023 can we change that, so the form can me parse?

**Comment by brianwdavis** [comment]
I will edit this manually

**Comment by kldriver** [comment]
offline as of 6/11. Email today.

**Comment by elhenriq** [comment]
asked tom to download data from this farm.

**Comment by elhenriq** [comment]
all good for this farm.
