### ISSUE TITLE
Water Sensors: VPE UGB MO

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#316]
Sensors installed, a form submitted, no data showing at all for VPE. Only awoke and sent a time update. Data not graphing for UGB but some is being sent to the dashboard. Only node 528 is communicating (Bare 2). The data it is sending is problematic.

**Comment by elhenriq** [comment]
talked to charles today! 

he made a mistake when installing the nodes and gateways and mix and match from two different farms. when he was there today he realized that there mixed and will fix ASAP.

downloaded data and will send to me for review

**Comment by kldriver** [comment]
R1C offline as of June 2
R2C missing middle sensor

**Comment by elhenriq** [comment]
this issue covers two farms!

**UGB**

R1C: not talking to the node (have to reset the farm to make it communicate again) and download data from the node. 
R1B: all good
R2C: B (middle) sensor needs to be looked at, reading -999 (possible solutions include checking for cuts on the wire and or rocks on the prongs). 
R2B: all good

**VPE**

reset entire farm. gateway is stuck on initialization. cant remember if we set it for Receiver only. download data from entire farm

**Comment by kldriver** [comment]
Poking Charles today

**Comment by kldriver** [comment]
UGB: Charles pulled the middle sensor for R2C and looked good. Probably needs a new sensor. Need to set to receiver mode. 

VPE: Need to set to receiver mode.

**Comment by elhenriq** [comment]
Charles visited VPE and downloaded all the data, everything seems to working great. I will review the data once I receive it

**Comment by kldriver** [comment]
VPE is completely offline

**Comment by elhenriq** [comment]
all looks good, for 3 of the nodes, Bare Rep 2 was not sending to the gateway, next time you visit this farm can you download directly from the node? 

sent an email to charles today.

**Comment by elhenriq** [comment]
have not send data for the last 2 weeks, asked charles to download data again.

**Comment by kldriver** [comment]
Data downloaded at end of season.
