### ISSUE TITLE
Water Sensors: FYL Indigo Brooke

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#317]
R1B (665) connected for 1 day then went offline. The other 3 nodes appear to have never made initial connections. 

When the gateway awoke, there were 3 missed nodes: 65 64 59

**Comment by elhenriq** [comment]
Hard reset on entire system call hotline!

**Comment by kldriver** [comment]
Emailed 6/1.

**Comment by kldriver** [comment]
Appears to have been serviced, the same thing as above happened, R1B went online for ~1 day and none of the other reps are graphing. The surface temperature sensor is also reading -999.

**Comment by kldriver** [comment]
Site is still completely offline. Poking today.

**Comment by elhenriq** [comment]
only one node talking here. have to check all 3 other sensors, make sure they are within line of sight of the gateway and ensure connection with other ones before leaving the field. 

download the data from all nodes and send to me.

**Comment by elhenriq** [comment]
this farm had multiple issues and was hard to diagnose, the corn is v11- v12 almost no data for 3 of the reps, one node need to be replaced, but I thought it was best to uninstall this farm. Brooke went ahead and remove the sensors. @saseehav
