### ISSUE TITLE
Water Sensors: HTT Indigo Brooke

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#318]
R1B: no deep sensor sending data.  (581)
R1C: There are short blips between 5/18 and 5/22 but no consistent data. (757)

**Comment by elhenriq** [comment]
R1C is missing completely from this farm, there is an issue with the configuration of the nodes and gateways! MUST CALL HOTLINE

R1B most definitely has a broken sensor after install

**Comment by kldriver** [comment]
Emailed 6/1.

**Comment by kldriver** [comment]
site is completely offline

**Comment by elhenriq** [comment]
Reset, download data from all nodes and gateway and put to receiver mode only. 

R1B c (deep) sensor not working check for wiring or a rock, might need a replacement.

**Comment by kldriver** [comment]
Site is completely offline. Poking today.

**Comment by elhenriq** [comment]
issues at bare rep one, most likely a loose cable that makes the node miss the data. all sensors read -999 at the same time. that happens when the sensors come disconnected from the node while it is on. 

cover rep one is not talking.

**Comment by kldriver** [comment]
Site online.

**Comment by kldriver** [comment]
Site completely offline, -999 in (581c). No litter sensor.

**Comment by elhenriq** [comment]
received data from this farm up to 7-5 and it has been reset since. will download data again next week.

**Comment by elhenriq** [comment]
no data for a while, asking to download again.

**Comment by kldriver** [comment]
All available Indigo data downloaded at end of season
