### ISSUE TITLE
Water Sensors: LNM Indigo Brooke

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#319]
R1B: Missing Deep sensor -999s (472)
R2C: missing middle and deep sensors -999s (609)
#308

**Comment by elhenriq** [comment]
Most likely broken sensor cables. if cables are ok. check junction boxes and make sure cables are properly seated

**Comment by kldriver** [comment]
Emailed 6/1.

**Comment by elhenriq** [comment]
looking at this farm i can see that the data comes in and out sometimes that leads me to believe that the issue is that the prongs are touching each other and need to be pull out of the ground and re-installed 

for Cover Rep 2 (middle and deep) for Bare Rep 1 (deep).

**Comment by kldriver** [comment]
followed up today

**Comment by kldriver** [comment]
Issues persist, will poke Brooke.

**Comment by kldriver** [comment]
Site online.
