### ISSUE TITLE
Forms were not on KoBo

### ISSUE THREAD

**Issue by deannrp** [precision-sustainable-ag/On-farm-Protocols#32]
When I went to get all of the blank forms there were only 2, not at all like shown on the YouTube tutorial.

**Comment by saseehav** [comment]
were you able to insert your username and password using the General Settings> Server on the Kobo collect app?
If this will not work, we can uninstall and re-install the app when your device is back online

**Comment by deannrp** [comment]
I was able to add my username and password but still can’t get to the forms

DeAnn Presley, from phone, please forgive typos
Work cell: 785-313-4193 (Best way to reach me)
________________________________
