### ISSUE TITLE
Water Sensors: MGT NC

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#320]
No data for R2C (55). Never made initial connection
21000210(10) Gateway awake at 5/22/2023 19:10. Synced to Nodes: 87 92 83 Missed Nodes: 55

**Comment by elhenriq** [comment]
@AlstonBetts will be checking these sensors this week

**Comment by kldriver** [comment]
R2C back online 5/31

**Comment by kldriver** [comment]
Site completely offline @AlstonBetts

**Comment by elhenriq** [comment]
all good
