### ISSUE TITLE
Water Sensors: OFP Indigo Brooke

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#321]
R1B: Never made an initial connection (589)
R1C: middle is reading 0, surface and deep appear to be struggling to pick an algorithm, no top sensor reading
R2B: top is reading 0, middle and deep are having a little trouble choosing and algorithm
R2C: Deep is reading very close to zero, and the middle sensor is struggling to choose an algorithm.

**Comment by elhenriq** [comment]
most likely solution is to do a re install on the entire set! or make sure all sensors are properly seated! these are the updated TDR's they should not be reading with multiple formulas.

**Comment by kldriver** [comment]
Emailed 6/1.

**Comment by kldriver** [comment]
Surface temp reading -999/99

**Comment by kldriver** [comment]
deep sensor not sending data

**Comment by elhenriq** [comment]
R1C: c (deep) sensor is not working, check cable and check for rocks. maybe need a replacement sensor
R1B: a (top) sensor is not working, check cable and check for rocks. maybe need a replacement sensor

**Comment by kldriver** [comment]
Issue persists, poking Brooke today.

**Comment by kldriver** [comment]
Poking today.

**Comment by elhenriq** [comment]
rep 1 bare is top sensor is still not working, rep one cover stop comunicating yesterday also need to check deep sensor

**Comment by kldriver** [comment]
Data now present.
