### ISSUE TITLE
Water Sensors: YPH Indigo Brooke

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#322]
21000212(12) Gateway awake at 5/13/2023 16:53. Synced to Nodes: 86 95 4 Missed Nodes: 16
all other nodes went offline 5/14.

**Comment by elhenriq** [comment]
checking into this one, I see activity from the gateway trying to connect but not being able to send data. needs to go out to the field and check it with the tablet. call hotline if needed

**Comment by kldriver** [comment]
Emailed 6/1.

**Comment by elhenriq** [comment]
farm hasnt updated on a week, will probably move to data collection only

**Comment by elhenriq** [comment]
no data for awhile, asking to download data soon.

**Comment by kldriver** [comment]
duplicate issue of #309. all data available downloaded at end of season
