### ISSUE TITLE
Water Sensors: HGU, ZEE WI

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#325]
HGU: most likely what is going on here is that your gateway does not have enough strength to communicate the data to the dashboard. let's troubleshoot it with the tablet, and maybe we can figure out what is going on. if we determine is not powerful enough, will set up on manual collection mode. 

ZEE: same issue as HGU 

ZTP: the sudden spike is most likely due to a rain event! that is ok 

Reply from Ashley: Tom is our field manager and would be the one to do the troubleshooting with you. I believe he is planning to go to the HGU and ZEE sites on Friday to get the litter bags, so that would probably be a great time to do the troubleshooting.

**Comment by kldriver** [comment]
we have been swamp with data collection over here, I will get the sensors in the mail for you this week, most likely on Thursday. 

HGU: most likely what is going on here is that your gateway does not have enough strength to communicate the data to the dashboard. let's troubleshoot it with the tablet, and maybe we can figure out what is going on. if we determine is not powerful enough, will set up on manual collection mode. 

ZEE: same issue as HGU 

ZTP: the sudden spike is most likely due to a rain event! that is ok

**Comment by kldriver** [comment]
Continues to be problematic. @elhenriq are these sites in receiver mode?

**Comment by elhenriq** [comment]
YES HGU and ZEE are
