### ISSUE TITLE
Water Sensors: OSC Indigo (164677) Brooke

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#328]
Sending data very inconsistently across the board ( 2 or three points a day) since 24 of May. Bandwidth issue?

**Comment by elhenriq** [comment]
yeah, the data usage for this device is very low, which leads me to believe that is having issues getting enough signal to send the data.

better to put on data collection only 


**Previous conversation with Brooke** 

maybe! we can try 


On Tue, May 30, 2023 at 3:03 PM Brooke Rohrig <[brohrig@indigoag.com](mailto:brohrig@indigoag.com)> wrote:
Can I try to move the gateway to better signal? This field is 5 hours from my house so very unlikely I can collect data that often

Get [Outlook for iOS](https://aka.ms/o0ukef)
From: Esleyther Henriquez <[elhenriq@ncsu.edu](mailto:elhenriq@ncsu.edu)>
Sent: Tuesday, May 30, 2023 12:24:44 PM
To: Brooke Rohrig <[brohrig@indigoag.com](mailto:brohrig@indigoag.com)>
Cc: Kayla Driver <[kldriver@ncsu.edu](mailto:kldriver@ncsu.edu)>
Subject: Re: question about water sensor chart view
 
your gateway is having issues connecting to the network and sending the data! from what I can see, the best course of action here is to move to a manual data collection mode. I can assist with that if you call the hotline. additionally, I see that your middle sensor on bare rep 1 is not working properly (most likely some broken cables). 

step by step what I would do is

1. download and save all data from the gateway
2. set gateway to receiver mode
3. download and save all data from the nodes (all four)
4. fix broken sensor in the field
5. send data to me from the field to check it and make sure all is good 
6. reset everything and make sure they talk (check with the tablet connected to the gateway) 
7. plan on coming back to get data every 2–3 weeks 

On Tue, May 30, 2023 at 10:06 AM Brooke Rohrig <[brohrig@indigoag.com](mailto:brohrig@indigoag.com)> wrote:
Good morning, I was looking through the chart views for my water sensors and I was wondering if you could give me some info on field OSC gateway number 164677. The graph only has a few dots every once in a while and im not sure what that means or how to fix it. thanks

**Comment by kldriver** [comment]
still irregularly sending data

**Comment by elhenriq** [comment]
R1C: a (top) sensor is very low, d (surface) sensor is very low
R1B: check b (middle), could be a broken cable, or rocks in the prongs. 
R2C: A (top) sensor is reading low.
R2B: A (top) sensor is reading low

need to reset all nodes and download data, set to receiver only

**Comment by kldriver** [comment]
Poking Brooke today.

**Comment by elhenriq** [comment]
Brooke visited this farm this week, and she has fixed the sensors on it. the gateway has very spotty signal. I asked to download the data, waiting to receive the files.

**Comment by kldriver** [comment]
Site online.

**Comment by elhenriq** [comment]
data very spotty asking to download soon. cover rep 2 has not been sending for a while.

**Comment by kldriver** [comment]
All available data downloaded at end of season.
