### ISSUE TITLE
Water Sensors: UZF Indigo (1084054) Tyler

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#329]
Online for the most part except R1B, all deep sensors really struggling to pick a formula. The most correct formula seems apparent for rep 2 but R1C (844) may need a new sensor.

**Comment by kldriver** [comment]
Emailed 6/1.

**Comment by elhenriq** [comment]
sending replacement sensors for both deep sensors on rep 2

**Comment by elhenriq** [comment]
sensor have been replace and data seem to be behaving better
