### ISSUE TITLE
Water Sensors: ZFW NC (1724912)

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#330]
All reps offline. 341 (b) was sending -999 before the whole site went offline. All other sensors were sending complete data.

**Comment by elhenriq** [comment]
visiting this farm this week! will replace the sensor

**Comment by kldriver** [comment]
All online, looking good.

**Comment by kldriver** [comment]
Whole site offline

**Comment by kldriver** [comment]
Site is back online.
