### ISSUE TITLE
Water Sensors: GXL Indigo (1084042) Tyler

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#331]
online for the most part rep onw middle sensors are struggling to pick a formula. the most desirable formula seems apparent enough that we may not need to send a replacement

**Comment by elhenriq** [comment]
I will send a replacement, it should not do that since it is a newer sensor.

**Comment by kldriver** [comment]
Emailed 6/1.

**Comment by elhenriq** [comment]
stop communicating yesterday, reset and download data, not urgent

**Comment by elhenriq** [comment]
received data from this farm, it looks good is on the drive.

**Comment by kldriver** [comment]
Site is completely offline.

**Comment by elhenriq** [comment]
sensors are working here all good, will most likely download data in another week

**Comment by kldriver** [comment]
Site is completely offline. Bothering Tyler about it today.

**Comment by elhenriq** [comment]
received data from this farm all good here

**Comment by elhenriq** [comment]
no data for 10 days, asking to download again

**Comment by kldriver** [comment]
All available data downloaded at end of season.
