### ISSUE TITLE
UCE AR ussing old equipment

### ISSUE THREAD

**Issue by elhenriq** [precision-sustainable-ag/On-farm-Protocols#333]
the team in AR never sent their nodes and gateway back to us. (we don't have a backup for the data they collected in 2022). They have already installed their old devices in the field for this season. We sent them new devices for this season with updated firmware for the gateway, but they might have misplaced them. I recommended to them to switch the old nodes and gateway with the new set we sent if they can find them, we could send another set for them if they can't find them to replace the ones they have in the field. 

The issue I see with keeping the old nodes installed in the field are:

1. We don't have a file for the data from last year for their farm (their data is mostly complete, but it worries me that the backup is missing).
2. The data on the device itself will be mixed up with this year's data if we were to wait to do a download at the end of the season.
3. Their gateway is running the old firmware where the gateway sometimes gets stuck if it loses connection and doesn't continue to collect data. 
4. They are limited to 2G network connections since they are running the old cellular board.

**Comment by kldriver** [comment]
Gateway Serial: 21000150
Device Code: 1084050

**Comment by elhenriq** [comment]
working all good
