### ISSUE TITLE
Water Sensors: GQD Indigo Brooke (280918)

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#334]
R2C isn't sending any data

**Comment by elhenriq** [comment]
sensors are not being recognize by the node, could be a broken cable or a lose cable.

**Comment by kldriver** [comment]
emailed today

**Comment by kldriver** [comment]
Rep 2 C began sending data 6/6. Whole site is offline as of 6/14.

**Comment by kldriver** [comment]
Site is still offline, poking today.

**Comment by elhenriq** [comment]
download data and reset the farm and send data to me.

**Comment by kldriver** [comment]
Site is still completely offline, no evidence of download in drive. Poking broke today.

**Comment by kldriver** [comment]
Available data downloaded at end of season.
