### ISSUE TITLE
Water Sensors: HFV Indigo Brooke (164671)

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#335]
R1B middle sensor isn't sending any data.

**Comment by elhenriq** [comment]
broken sensor need to be replaced sending replacement tomorrow

**Comment by kldriver** [comment]
R2B deep sensor is sending noisy data, R1 Middle still offline

**Comment by kldriver** [comment]
Poking today on R1B middle

**Comment by kldriver** [comment]
Poking again on R1B

**Comment by kldriver** [comment]
R1B middle sensor 489 offline still

**Comment by kldriver** [comment]
Site is completely online.
