### ISSUE TITLE
Water Sensors: IGJ Indigo Brooke (1084034)

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#336]
R1B deep sensor is struggling to pick a formula
R2B top sensor sent 2 blips then never again
R2C node appears to have never made an initial connection.

**Comment by elhenriq** [comment]
R1B, try and drive the sensor in a bit more. that is a new sensor and should be reading properly. maybe a rock on the way. 

R2B sensor was reading as -999 i will send a replacement sensor just in case. please check all the wiring! and make sure sensor is actually broken before replacement 

need to restart system to get R2C back in schedule, also download data from it. can call hotline if you need help

**Comment by kldriver** [comment]
emailed today

**Comment by kldriver** [comment]
looks to have been serviced this week. R1 B looks good. R1C surface sensor is reading 0 sometimes, air? Rep 2 B middle sensor is still very noisy but top is back online. R2C is online, sending semi-irregularly but missing deep sensor.

**Comment by elhenriq** [comment]
Replace entire set of sensors for bare rep 2, send cover rep 2 set. rep 2 bare middle (check for bent)

**Comment by kldriver** [comment]
Site is completely offline

**Comment by elhenriq** [comment]
all good now
