### ISSUE TITLE
Water Sensors: KLB Indigo Brooke (1022428)

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#337]
R1B deep sensor isn't sending data
R2C top sensor isn't sending data, deep sensor is sending data that doesn't look real

**Comment by elhenriq** [comment]
most likely broken cables at the top of the sensor. will send replacements. or a rock in between the prongs.

**Comment by kldriver** [comment]
issues persist. Poking Brooke today.

**Comment by kldriver** [comment]
Poking today.

**Comment by elhenriq** [comment]
bare rep 1 is having -999 on deep sensor, need to replace the sensor
cover rep 2 is having -999 on top sensor, need to replace sensor, deep sensor is not all the way in it is reading zero.

**Comment by kldriver** [comment]
Poking today

**Comment by elhenriq** [comment]
no data for the last week, asking brooke to download again, also deep sensor cover 2 is reading zero.

**Comment by kldriver** [comment]
Available data downloaded at end of season.
