### ISSUE TITLE
Water Sensors: WJR Indigo Tyler (164681)

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#338]
This site is completely offline.

**Comment by elhenriq** [comment]
reset and download data, most likely need to move to receiver mode only

**Comment by elhenriq** [comment]
gateway was moved to receiver mode! downloaded data from all nodes and i will upload the files.

**Comment by elhenriq** [comment]
data seems good

**Comment by elhenriq** [comment]
Received downloaded data, all good. added to the drive

**Comment by elhenriq** [comment]
asking for data again two weeks with no download.

**Comment by kldriver** [comment]
Available data downloaded at end of season.
