### ISSUE TITLE
Water Sensors: GWP KS (1084044)

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#340]
R2C is offline and never started sending data

**Comment by elhenriq** [comment]
the node is actually connected, there is an issue with the sensors connected to cover rep 1. (no sensors are being read). have to visit the farm and check on connections.

**Comment by kldriver** [comment]
emailed today.

**Comment by kldriver** [comment]
Fully online.

**Comment by kldriver** [comment]
R1C middle sensor is reading 0 and the deep is close to 0
R2B deep sensor has 2 full lines due to messy data. Replacement? 
R2C middle sensor has 2 full lines due to messy data. Replacement?

**Comment by kldriver** [comment]
GWP rep 1 cover: pushed the sensors in farther to make better contact and seems to be working correctly.
