### ISSUE TITLE
Water Sensors: RVP VA E (1084052)

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#341]
This site is completely offline as of 5/29.

**Comment by elhenriq** [comment]
farm needs to be reset! download data from gateway and each node and send to me

**Comment by kldriver** [comment]
emailed today.

**Comment by kldriver** [comment]
Fully online.

**Comment by kldriver** [comment]
The site is completely offline. Poking Joey today.

**Comment by kldriver** [comment]
Site is completely offline. Following up today.

**Comment by elhenriq** [comment]
farm fully functional now. have not received a file from Joey
