### ISSUE TITLE
Water Sensors: WLL (280927) Indigo Tyler

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#342]
R1C offline as of June 2.

**Comment by elhenriq** [comment]
download data from this node and reset entire farm to make connection with this node

**Comment by kldriver** [comment]
Rep 1 Cover offline

**Comment by kldriver** [comment]
Poking today. Rep 1 C still offline.

**Comment by elhenriq** [comment]
data coming in now.
