### ISSUE TITLE
Water Sensors: KGR (1084038) NE

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#344]
KGR R2B is missing the top sensor.

**Comment by kldriver** [comment]
Issue persists: poking again today.

**Comment by kldriver** [comment]
Poking today.

**Comment by elhenriq** [comment]
this farm was removed from study due to not having enough biomass, they will keep the sensors for use for Tauana PhD. will reset and download data also check on cover rep 1 middle sensor.

**Comment by elhenriq** [comment]
no data for a while
