### ISSUE TITLE
Water Sensors: PSN Indigo Brooke (293875)

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#345]
R1B Missing middle Sensor, top sensor is irregularly sending data
R2B Sent small blip on jun 5, offline since

**Comment by elhenriq** [comment]
R1B: a (top) is reading zero, check for proper installation. b (middle) sensor is not working well. check for broken cable or rocks in the prongs (maybe replace sensor).
R1C: T (temp) is reading 2.86 I think this needs to be replaced. 
R2C: A (top) sensor is reading low.

**Comment by kldriver** [comment]
Issues persist, will poke Brooke today.

**Comment by kldriver** [comment]
Following up today.

**Comment by elhenriq** [comment]
download data from rep 2 bare. check cables rep 1 bare | rep 1 bare top sensor, rep 2 bare node not talking

**Comment by kldriver** [comment]
Site is online.

**Comment by kldriver** [comment]
Rep 1 bare sensor offline. No (d) in string

**Comment by elhenriq** [comment]
no data for a while now, asking for donwload again.

**Comment by brohrigindigo** [comment]
Sent downloaded data today

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kldriver** [comment]
all available data downloaded at the end of the season.
