### ISSUE TITLE
Water Sensors: UJC Indigo Tyler (1724921)

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#346]
R1B deep sensor is irregularly sending and struggling to pick a formula
R1C deep sensor is not present, all other sensors online
R2B missing deep sensor

**Comment by elhenriq** [comment]
R1C: c (deep) needs to be revised (maybe replaced) ill send sensors for this farm 
R1B: c (deep) needs to be revised (maybe replaced) ill send sensors for this farm 
R2B: C (deep) needs to be revised (maybe replaced) ill send sensors for this farm

**Comment by elhenriq** [comment]
deep sensors at this farm were replaced on 6/20. the sensors are reading better now but still some issues, on R1B and R2B. asking to take a look again.

**Comment by elhenriq** [comment]
Bare rep 2 node (18001822), needs to be replaced, the node quit responding and won't do anything, I will send a new node ASAP.

**Comment by elhenriq** [comment]
sending 18001968 to replace this node.

**Comment by elhenriq** [comment]
no data for a while, asking to download again.

**Comment by kldriver** [comment]
For 2023 water shepherding: Bare rep 2 node (18001822) replaced by (18001968).

**Comment by kldriver** [comment]
nothing more to do.
