### ISSUE TITLE
Water Sensors: WBN Indigo Brooke (280907)

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#347]
R1B Missing deep sensor

**Comment by elhenriq** [comment]
R1C: a and d (top and surface) are reading a bit low, maybe check proper installation (could be ok depending on field conditions). 
R1B: c (deep) needs to be checked ( maybe replaced) check for cuts in the cable or rocks at the prongs. 
R2C: A (top) is very low check for proper installation! 
R2B: A (top) is very low check for proper installation!

**Comment by kldriver** [comment]
Following up today.

**Comment by elhenriq** [comment]
broken cable most likely | rep one bare deep sensor not working since beginning

**Comment by kldriver** [comment]
Poking today

**Comment by brohrigindigo** [comment]
I replaced the sensor last week and was getting readings when I plugged the tablet in along with readings on the device status now but it’s not graphing.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kldriver** [comment]
Rep 1 Bare is missing the deep sensor and Rep 2 Bare node is completely offline.

**Comment by kldriver** [comment]
Available data downloaded at end of season.
