### ISSUE TITLE
tech dashbouard not loading on tablet

### ISSUE THREAD

**Issue by tabpetri** [precision-sustainable-ag/On-farm-Protocols#35]
sarah on esper with tablitha trying to load tech dashbouard. git hub is authenticated but stuck on loading page

**Comment by brianwdavis** [comment]
Hi Tabitha, were you able to get Tech Dashboard to load yet? I'd like to
troubleshoot any problems you're having.

**Comment by saseehav** [comment]
@tabpetri Hi Tabitha,
Following up on this issue. Were you able to get Tech Dashboard to load on your tablet?

**Comment by tabpetri** [comment]
Hi Sarah, Yes! After restarting the tablet a couple days later, the Tech Dashboard loaded. Should be good to go now! Sorry, I forgot to mention this to you. Brian followed up with me about it during our last PSA meeting and it was working by then. Thank you for your help!
