### ISSUE TITLE
Water Sensors: TOI NC (280929)

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#351]
R2B deep sensor is quite noisy, probably needs replacement sensor or reinstall

**Comment by elhenriq** [comment]
@AlstonBetts will take a look at the installation. I have a suspicion that it might have a rock in between the prongs and that causes the noise.

**Comment by kldriver** [comment]
Deep sensor looks normal now, all nodes online.
