### ISSUE TITLE
Water Sensors: POQ NE (1084049)

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#352]
R1B offline since jun 2
R1C appears to have never made initial connection
R2B appears to have never made initial connection
R2C offline since jun 2

**Comment by elhenriq** [comment]
hard reset, and call hotline before leaving the field maybe move to receiver mode only

**Comment by kldriver** [comment]
Tauana's visit Wednesday did not resolve the issues. Will poke today.

**Comment by kldriver** [comment]
Issues persist. Poking today.

**Comment by elhenriq** [comment]
talked to tauana today, and they are visiting the farm and will download data from this farm and send to me. they will also replace a water sensor they broke.

**Comment by elhenriq** [comment]
received data from 6-28 and all is good added files to the drive

**Comment by elhenriq** [comment]
no data from this farm for a while asking to download again

**Comment by kldriver** [comment]
all available data downloaded at the end of the season.
