### ISSUE TITLE
Water Sensors: AHW VA E (280908)

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#353]
R1B Deep sensor is sending -999, Temp sensor sending -999

**Comment by elhenriq** [comment]
R1C has issues with d (surface) and T (temp) most likely the temp sensor went bad and is messing up the surface sensor. it could also be a broken cable on either sensor. i will send a replacment T for this farm. 

R2C i would like to replace the deep sensor. old sensor model
R2B i want to replace the middle sensor. old sensor model 

**will send replacement today**

**Comment by kldriver** [comment]
Completely online

**Comment by elhenriq** [comment]
rep cover 2 is not sending data for the last week, asking Joey to check on that node.

**Comment by kldriver** [comment]
all available data downloaded at the end of the season.
