### ISSUE TITLE
Water Sensors: YAA VA W (1724901)

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#354]
R1C appears to have never made initial connection

**Comment by elhenriq** [comment]
the node is communicating with the gateway, the issue there is that the node is not recognizing the sensors, which means no data is being collected. 

R2C is reading very low on the top sensor (most likely not in all the way).

**Comment by kldriver** [comment]
Issues persist. Poking Cynthia today

**Comment by elhenriq** [comment]
sent this today.

Hello Cynthia

looking at this farm, you have both nodes from the cover crop reps that are not reading the sensors. most definitely, they have a problem with the connection from the sensors to the node. broken cable between the node and sensors or a loose cable on the junction boxes. I will send you two new set of sensors for these farms, but again, I don't think that's the issue. once you receive the sensors, please send all the unused sensors you have with you, broken or good.

**Comment by kldriver** [comment]
Site is online.
