### ISSUE TITLE
Water Sensors: DKP VT (1084033)

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#355]
R2B Top sensor isn't sending data

**Comment by elhenriq** [comment]
Previously talked to Lindsey

CT1: a & b (top and middle) sensors are reading very low compared to the rest, I would check them to make sure they are properly installed. 
BT1: your d (surface) sensor is reading low. 
CT2: B (middle) sensor is reading around 10%, but compare with the other ones maybe should be higher. 
BT2: A (top) needs to be replaced (will send new sensor tomorrow). and C (deep) is also reading very low around 6% which is very unlikely to happen.

**I just notice that it also needs a new temp sensor. I will send a new Temp and deep sensors for R2C and R2B**

**Comment by kldriver** [comment]
Fully online.

**Comment by elhenriq** [comment]
has not sent data for the last week asking to check on them.

**Comment by kldriver** [comment]
nothing to be done.
