### ISSUE TITLE
Water Sensors: EJU VT (1084048)

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#356]
all offline may 11, -999 in temp sensor

**Comment by elhenriq** [comment]
I checked this farm on the tech dashboard (device status view) and all is working fine as far as sending data .

R1C: middle and deep are reading 42 and 55 percent of water; maybe a bent TDR prong. it could be real if really wet field. 
R1B: b (middle) is reading zero. most likely air pockets and the sensor is not all the way in. 
R2C: A and B (top and middle) are reading really close to zero. most likely not all the way in. 
R2B B (middle) is reading zero. most likely an air pocket.

**Comment by kldriver** [comment]
online since 6/9. Very noisy data in 1B middle and 2C middle reinstall these sensors?

**Comment by elhenriq** [comment]
not sure what to do here! so much noise from everything. @saseehav what do you think?

**Comment by elhenriq** [comment]
working good now, data still noisy but usable.
