### ISSUE TITLE
Water Sensors: TZM VT (280933)

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#357]
R2C middle sensor is reading strangely close to zero

**Comment by elhenriq** [comment]
I had communicated with Lindsey already, here is what I told her about this farm.

R1C: d (surface) is reading low. also it is an older version of the TDR's ill send you a new sensor for it. 
R1B: b (middle) is reading zero, most likely in an air pocket.
R2C: B (middle) is not working properly, I would check on the wiring for that sensor but just in case ill send a replacement. 
R2B: B (middle) might be ok but check just in case it is reading lower than everyone else.

**Comment by kldriver** [comment]
The middle sensor stopped reading June 15.

**Comment by kldriver** [comment]
Following up today.

**Comment by kldriver** [comment]
Site is completely offline.

**Comment by elhenriq** [comment]
data good now
