### ISSUE TITLE
Water Sensors: YUO FL (1827725)

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#360]
Offline since 6/17/2023. Not sending data from node R1B 433. Made initial connection.

**Comment by kldriver** [comment]
Esleyther: Gateway is connecting but the connection is not strong enough. Put in Receiver Mode.

**Comment by elhenriq** [comment]
i believe this farm has not been installed yet.

**Comment by kldriver** [comment]
YUO came online 7/7 and went offline 7/9. Completely offline.

**Comment by elhenriq** [comment]
working good now
