### ISSUE TITLE
Water sensors UGB MO (1724908)

### ISSUE THREAD

**Issue by elhenriq** [precision-sustainable-ag/On-farm-Protocols#362]
Two of the nodes at this farm got water inside of them and will need to get replaced. i will ship replacements for them by the end of the week. 
18000430 cover rep 2
18000451 cover rep 1

Additionally, Charles visited this farm and downloaded all the data from the gateway and all the data seems to be present. will send the files to me and i will check again for anything i might have missed.

**Comment by kldriver** [comment]
Site is completely offline. Rep 2 Cover middle sensor went off before the whole site.

**Comment by elhenriq** [comment]
Charles replaced two of these nodes a little bit ago, all the nodes are working fine, but it is not reflected on the charts since hi has not submitted the form (I don't think).

**Comment by AlstonBetts** [comment]
Looks like he submitted a install form on June 29th and put "winter" instead of reinstall

**Comment by saseehav** [comment]
UGB Rep 1 - Cover Middle depth sensor not operating correctly. replace
<img width="400" alt="image" src="https://github.com/precision-sustainable-ag/Hotline-Issues/assets/49722541/288cfcf0-b537-4ad7-9a5b-27edb427e6c9">

**Comment by elhenriq** [comment]
i sent a replacement to charles, he has replaced it now, aslo asked him to download data again.

**Comment by kldriver** [comment]
shepherds: make sure change of node is reflected in dataset.

**Comment by kldriver** [comment]
sensor install form details the node changes. nothing more to do
