### ISSUE TITLE
Water Sensors: INN AL (280914)

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#363]
Rep 1 C top sensor is spiking pretty high. Check the gasket.

**Comment by elhenriq** [comment]
seems good to me

**Comment by kldriver** [comment]
R1C top sensor is reading -999 node 791 sensor 735

**Comment by elhenriq** [comment]
top sensor for both cover and bare rep 1 were eaten by animals. i will send replacements today. ![image](https://github.com/precision-sustainable-ag/Hotline-Issues/assets/52674578/98ac058b-8308-4424-94e9-396ac8f680b4)

**Comment by elhenriq** [comment]
all good
