### ISSUE TITLE
Water Sensors: SMS Indigo Tyler

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#367]
R1C top sensor is problematically noisy.

**Comment by kldriver** [comment]
Rep 1B deep sensor is reading -999

**Comment by kldriver** [comment]
Site completely offline

**Comment by elhenriq** [comment]
received all data download from this farm all look good

**Comment by elhenriq** [comment]
no data for a while asking to donwload again.

**Comment by kldriver** [comment]
Available data downloaded at end of season.
