### ISSUE TITLE
Water Sensors: WRE Indigo (1022434)

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#369]
This site is completely offline.

**Comment by kldriver** [comment]
Whole site offline still, poking today

**Comment by kldriver** [comment]
No biomass data, water data not pertinent for our purposes.

**Comment by elhenriq** [comment]
received some files from lee today this is what i saw

WRE
Bare Rep 1: I did not receive a file for this one
Cover Rep 1: the battery died on 6-20,I so no data after that.
Bare Rep 2: I did not receive a file for this one
Cover Rep 2: I did not receive a file for this one. 

I notice you kept trying to get the gateway to talk again, but were not successful. please go back to this farm and try and download data from each node, please send to me as soon as you get it, so I can review and give you help if needed.

**Comment by elhenriq** [comment]
no daa for the last month and a half asking lee to download again.

**Comment by kldriver** [comment]
all available data downloaded at the end of the season.
