### ISSUE TITLE
Trouble downloading forms and logging onto KOBO server

### ISSUE THREAD

**Issue by ethansweep** [precision-sustainable-ag/On-farm-Protocols#37]
Customer: Shalamar Armstrong, Purdue University

Shalamar sent a text message to the PSA hotline stating that he was unable to find fillable forms through the ODK Collect App. 
Responder gave him instructions, with pictures, showing him how to "Get Blank Form(s)" from the ODK home page. Shalamar responded with a picture that he could not connect to the server, where we noticed he was connected to https://kc.kobotoolbox.org. We then instructed him to change the address to kf.kobo and included a link to the ODK Quick Start Guide.
Shalamar responded that they got it to work.

**Comment by brianwdavis** [comment]
Maybe we should add a direct link to instructions/protocol from the user/pass section of Tech Dashboard.

**Comment by ethansweep** [comment]
Today I tried logging onto the ODK Collect server from our old tablet. When I went to enter our information I entered the kf.kobo address and it wouldn't let me connect to the server. I then tried entering the kc.kobo address and I was able to connect to the server. I'm not sure what to make of this.

**Comment by saseehav** [comment]
@Ethan Sweep ***@***.***> can you link this quick start guide
you sent so the server can be corrected?

**Comment by ethansweep** [comment]
[https://docs.google.com/document/d/1rsSmhmEXTms_MDP745cyEUPTWbbvA34DU4A3jPc34qI/edit?usp=sharing](https://docs.google.com/document/d/1rsSmhmEXTms_MDP745cyEUPTWbbvA34DU4A3jPc34qI/edit?usp=sharing)

Here's the link to the ODK quick start guide.
