### ISSUE TITLE
water sensors NBS FL

### ISSUE THREAD

**Issue by elhenriq** [precision-sustainable-ag/On-farm-Protocols#371]
talked with David at FL today, they installed their sensors about a week ago, when they installed the nodes for rep one were backwards (cover into bare and bare into cover). they will switch them next week once rain has stopped. additionally, I asked him to download data from all node since one of them is not sending to the gateway. 

the gateway at that farm is not recognizing the SD card, so it's sending data every 15 min, they will check on that too. 

when they do the switch, they will notify me so that I can write down in here that date for us to update the data showing. (from day of install to date of transfer, data showing for bare rep one is supposed to be for cover rep one and vice versa).

**Comment by kldriver** [comment]
R2C 564 is completely offline

**Comment by kldriver** [comment]
Site is online.
