### ISSUE TITLE
Water sensors ZEE WI

### ISSUE THREAD

**Issue by elhenriq** [precision-sustainable-ag/On-farm-Protocols#372]
farm is on receiver mode 

data was downloaded on 6-19 and data all is looking good. i have submitted the files.

**Comment by saseehav** [comment]
@brianwdavis can we get this file parsed into the chart view? https://drive.google.com/drive/u/0/folders/1-L0mjVtlEfQrDLej0rcetQ867ZZNO3Nr

**Comment by saseehav** [comment]
Brian parsed the files downloaded. communicate with the WI team the next time they reach out that they can see their files.

**Comment by elhenriq** [comment]
no data for the last 2 weeks asking to download again.

**Comment by kldriver** [comment]
Available data downloaded at end of season.
