### ISSUE TITLE
Water sensors FSX AL 

### ISSUE THREAD

**Issue by elhenriq** [precision-sustainable-ag/On-farm-Protocols#374]
farm on receiver mode

data was downloaded on 6-20 and all data seems good.

needs a new temp sensor for cover rep 1. will send one ASAP

**Comment by elhenriq** [comment]
still need to receive the complete files from Kip.

**Comment by elhenriq** [comment]
asking kip for more data, hasn't communicated in a while.

**Comment by kldriver** [comment]
Available data downloaded at end of season.
