### ISSUE TITLE
Water Sensors: XNU Indigo

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#378]
Rep 1 Cover (441) online, but no data is coming in 
Rep 1 Bare (531) deep sensor is offline because there are -999s in the data string

**Comment by elhenriq** [comment]
checking on these sensors, the temp went bad and stopped all the other sensors from reading. Jake removed the temp sensor and was able to fix cover rep 1. there is no temp at this farm anymore I don't have replacements for it. 
also sending deep sensors for both rep 1 cover and bare.

**Comment by elhenriq** [comment]
working good now.
