### ISSUE TITLE
Confusion about minimum required width of strip plots

### ISSUE THREAD

**Issue by aidabagheri** [precision-sustainable-ag/On-farm-Protocols#38]
Customer: Tabitha, University of Florida

Tabitha was confused about the minimum required width of strip plots on-farm as told by the [PSA On-Farm Overview ](https://docs.google.com/document/d/113egv4qi2qYuWIMdy7NQJ6h1857Yxfwq/edit), and was unsure if she met the required width. The overview mentions that "All strip plots must be at least double the combine header being used by a given farmer" but also that the width should be "no less than 30 to 40' ". Her strips are not double the combine header, but they are 35' wide - does she meet the minimum width? Do both requirements need to be met or just one?

I answered that I was unsure and that I would contact her further if the 35' width was an issue

**Comment by brianwdavis** [comment]
I thought the language was clear, but we can clarify it further:

> All strip plots must be **at least double** the combine header being used by a given farmer and a minimum of 300’ long. Many farmers choose to continue these strips the entire length of field. Width **no less than 30 to 40’**

To me that means "minimum 2x combine width OR 30', whichever is greater". For this particular case, it could work, if we know where the grower will be driving the center pass on each one. How wide is the combine?

**Comment by brianwdavis** [comment]
Alternatively, we can just move forward with this site and make note to not import the automated combine data, use only the hand-yield data.

**Comment by screberg** [comment]
I think that would work.  Losing the combine data is not the end of the
world.


Chris Reberg-Horton

Professor of Cropping Systems

University Faculty Scholar

Department of Crop and Soil Sciences, Campus Box 7620

NC State University

Raleigh, NC 27695-7620

919 515-7597

***@***.***

**Comment by brianwdavis** [comment]
@aidabagheri Was this question resolved back to Tabitha?

**Comment by aidabagheri** [comment]
Yes, I confirmed with Tabitha that she can move forward with the site. 

Also, the grower's combine is 25ft so each rep is about 1.5 combine passes
