### ISSUE TITLE
Water Sensors: CWZ DE

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#386]
Site completely offline. Rep 2 bare had issues before entire site went offline

**Comment by elhenriq** [comment]
R1B 
the surface sensor for this treatment is reading zero for a while, most likely what is happening here is that the sensor is not in full contact with the soil and is on an air pocket. 
R2B 
the sensors at this treatment are having bad connections they keep coming in and out on reading data, can you go out and check on the connections there and make sure there are no loose cables creating issues.

**Comment by elhenriq** [comment]
not communicated for a while now, asked to download data.

**Comment by kldriver** [comment]
all available data downloaded at end of season
