### ISSUE TITLE
Water Sensors: YQU Indigo (164667)

### ISSUE THREAD

**Issue by kldriver** [precision-sustainable-ag/On-farm-Protocols#387]
Rep 1 Cover offline. Site appears to have been serviced yesterday (7/12).

**Comment by elhenriq** [comment]
received data from this farm all looks good. will download again next week.

**Comment by elhenriq** [comment]
no data for a while asking to download again soon.

**Comment by kldriver** [comment]
all available data downloaded at the end of the season.
