### ISSUE TITLE
Weeds3D: connectivity - 'error downloading' message from GoPro to tablet

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/On-farm-Protocols#392]
Email from Suranga: Hi Sarah and Zack,

I have the newest version of 3D weed app and scanned CE2 weed plots two days ago (timing 2). Before scanning the last two plots, Go Pro disconnected and never reconnect (appear to be connected but not recognizing I guess??). I tried resetting the connection but did not work. All the scanned videos are there in the Go Pro, but they cannot download from the Go Pro to the tablet, comes up as an ‘error downloading’. It seems Go Pro is connected to the tablet but not recognizing it. Try resetting the connection, wi-fi troubleshooting etc..etc… but it did work, …H..E..L..P..

 

Suranga

**Comment by marialauracangiano** [comment]
Fixed. He didn't have the WiFi password for the GP in the tablet and that was preventing him from stablishing a connection between the two devices. He was downloading the videos when we ended the call.
