### ISSUE TITLE
Water Sensors: TOI NC

### ISSUE THREAD

**Issue by AlstonBetts** [precision-sustainable-ag/On-farm-Protocols#399]
Gateway for TOI has stopped connecting to the network.
- There is no noticeable damage to the gateway, it randomly stopped connecting. According to the tech dashboard device status, it connected 9 hours ago (8:42 am 7/24), but the data is from 7/13   

I'm going to replace the gateway with a new one

**Comment by elhenriq** [comment]
data all good now
