### ISSUE TITLE
Expected Time for Tasks - Biomass and Decomp Bag Creation

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/On-farm-Protocols#4]
Expect 1 to 4 hours depending on biomass size and # of people involved.  1 hour 40 minutes seems to be the standard for practiced teams of 2 people.  

Tips for speed: 
we are + or - a few grams when we make the decomp bags fresh
good wind control for the scale
(speaking of scales, I've heard arguments for fresh weights being so far off with moisture that a half a gram accuracy is plenty. but we can have that discussion further after this spring with new people and aligning all our scales)
We clip a lot of extra biomass to mix in with our original quadrats after we weigh them.  This helps us not care how much falls on the ground.  
If the biomass is extra tall it's hard to stuff in the bag, so I cut it with scissors a few times (but not too much) before I start stuffing.  
Going right before termination is nice, because you don't have to be so careful with PPE (re: also for grinding too!)
We've already scouted the field so we know about where our subplots will be

**Comment by saseehav** [comment]
Any more tips for speed or time for biomass harvest?

**Comment by ethansweep** [comment]
This is a really great list, Sarah!
Something that I do if the biomass is extra long is clip it in half while I'm putting it into the tub to weigh it. This way it's easier to pull the samples out of the tub after weighing and right into the decomp bags.
We also find it best to collect two samples from the first subplot as a team, then one person goes back to weigh and fill decomp bags while the second person collects the other two samples.
