### ISSUE TITLE
Water Sensors: TOI data on dashboard

### ISSUE THREAD

**Issue by AlstonBetts** [precision-sustainable-ag/On-farm-Protocols#400]
The data I see on the TOI chart view is confusing to me. I uploaded the data files of all 4 nodes to the google drive on Friday 7/21. Before last Friday, all node data stopped at the same time on 7/13, when the gateway stopped connecting to the network. Checking the chart view this morning and I see extra data from rep 2 of this site has since uploaded, but on device status the last data point it's showing is from 7/13. It's also saying the gateway was active 9 hours ago, but according to the device status view it hasn't uploaded any new data since 7/13.  Was that data uploaded by the gateway?   @brianwdavis

**Comment by elhenriq** [comment]
data all good now
