### ISSUE TITLE
AgIR: change background color of Imaging Edge app

### ISSUE THREAD

**Issue by marialauracangiano** [precision-sustainable-ag/On-farm-Protocols#401]
Email from Reginald Fletcher: Is there a way to change the background color of the Image Edge Mobile App. It is difficult to see the information on screen when outside.

**Comment by zackgrzywacz** [comment]
Unfortunately there is no way to change the background color of the Imaging Edge app

**Comment by marialauracangiano** [comment]
Yeah, that's what I thought. I did a little bit of googling but couldn't find anything.
