### ISSUE TITLE
Missing Ethernet cable

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/On-farm-Protocols#424]
Zack - can you send Christopher Bernau the 10 ft ethernet cable? 

Good Morning Sarah,

 
We are missing the 10ft ethernet cable. We received everything else.

 
Thank you,

Christopher Bernau

Great Basin Plant Materials Center Manager

USDA-NRCS

2055 Schurz Highway,

Fallon, NV 89406

775-423-7957  ext. 4

**Comment by zackgrzywacz** [comment]
Contacted user and found the ethernet cable in their box. May be something to keep in mind for other users, the cable is in the Oak-D box under the camera.

**Comment by saseehav** [comment]
Thanks Zack. I'll plan to send that notification to the PMC USERS
