### ISSUE TITLE
Qr code won't open a site on Esper tablets

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/On-farm-Protocols#426]
On Sarah's new managed device, 4G model, blueprint 'PSA', the QR code will can but will not open the chrome browser. I filed a ticket with Esper.

**Comment by kldriver** [comment]
Esper made changes to my tablet (alias: Kayla) in Esper. Unsure of the mechanism by which they made the fix. Following up with them to see how we can fix this across the board and prevent this issue in the future with other tablets.

**Comment by kldriver** [comment]
From Esper Support: 
 
I would like to inform you that all the devices have already been updated to the latest version of Esper Agent.
