### ISSUE TITLE
FL Cover Crop Biomass and Farmer Reports

### ISSUE THREAD

**Issue by campbelldavidn** [precision-sustainable-ag/On-farm-Protocols#441]
The farmer reports for 2021 (BGP and NTK) have reported cover crop yields and a comparison with other area growers, but all others do not (DGF, NMO, NBS, and YUO). 

Was the report changed after the first year to exclude that graph?
Should the other sites have at least the cover crop biomass yield listed?

Also, would you please share how you calculated the cover crop biomass dry weight (DW) yield? I presume the calculation is based on the fresh weight yield, moisture % from T0, and a correction for ash was used to calculate that value, but my estimates of DW yield (calculated from data from the API, decomp) are slightly elevated from what was shown on the farmer report. 

Thank you!

**Comment by saseehav** [comment]
Brian found that the cc biomass API was calling the ash corrected biomass so it wasn't showing in the farmer reports. @brianwdavis fixed
