### ISSUE TITLE
Convert protocols to markdown?

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/On-farm-Protocols#5]
I don't know if this is worth the effort or not... But for storing plaintext on github it's really the best. 
> For example, the beginning of the biomass/decomp protocol:

```
CROWN Biomass and Decomp bag protocol
---

**Overview:**

This protocol is used for 2 main data collection points. 

1. **BIOMASS:**  First, we harvest 1 m<sup>2</sup> area of biomass, and will use the fresh weight of biomass recorded in the field, and a subsample of this dried back in the lab to estimate the total biomass, and biomass N contributed by the cover crop.  This biomass information is communicated to growers, and used in cover crop models, including the water sensor model.  

2. **DECOMPOSITION:** Second, we use the harvested fresh biomass in decomposition or litter bags to create a model of decomposition rate of the cover crop over the following growing season.   

![](path/to/diagram/in/repo.png)

```

> Renders on github.com as:

CROWN Biomass and Decomp bag protocol
---

**Overview:**

This protocol is used for 2 main data collection points. 

1. **BIOMASS:**  First, we harvest 1 m<sup>2</sup> area of biomass, and will use the fresh weight of biomass recorded in the field, and a subsample of this dried back in the lab to estimate the total biomass, and biomass N contributed by the cover crop.  This biomass information is communicated to growers, and used in cover crop models, including the water sensor model.  

2. **DECOMPOSITION:** Second, we use the harvested fresh biomass in decomposition or litter bags to create a model of decomposition rate of the cover crop over the following growing season.   

![](path/to/diagram/in/repo.png)

> Obviously with a real image there, instead of a broken image link.

This way we can have collaborative editing and diff tracking. But is it worth the time investment over storing .docx files?

I personally like markdown a lot because I use in in R notebooks, and it's a nice balance between something like LaTeX for document formatting and Word, while giving you the source-code-plaintext-feel you want for document tracking.

**Comment by brianwdavis** [comment]
And because this is a big-picture issue, I'm going to assign @screberg

**Comment by screberg** [comment]
I was just prosticating in issue #1 about whether we needed protocols in github or not.  I really don't have an opinion yet.  We could give it a go and see what we think.  I'll convert a few to markdown and let's give it a whirl.
