### ISSUE TITLE
On-Farm biomass sampling questions

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/On-farm-Protocols#50]
Lindsey from VT asked:
I have a few questions about proceeding with sampling processing.

1. How important is it that samples are dried for 48 hours? The samples I took today are not proliferous and I expect that they will be dry by tomorrow.
2. Our Wiley Mill grinds to 2mm. Is it okay to put them through the Udy to get them down to 1mm?
3. I submitted a couple of forms today.  Can you see them on your end. : )
4. I don’t have a ton of experience ordering equipment. We don’t have any augering equipment. Is our best bet to buy the Auger Power kit (we have a drill), 1 ¼” AMS Triple Flighted auger (we have heavier soils as opposed to sandy), and the 1-¾” Flight Auger? If we get those three items, will we be all set to install the sensors?

Sarah answered:
How did your first sampling go?

1. It is not important that they dry for 48 hrs, that is just recommended and typical for a fresh sample. They are dry when they are dry. Best practices for weighing anything is to pull them out of the oven at 48 hrs or when you think they are dry, weigh the sample, then continue drying for 24 hours and re-weigh the sample to check for change in weight. We don't require that. 

2. Sure, you can grind the samples in anything you like.

3. I can see LKB biomass and pre-weights. anything else?

4. I don't recommend a drill. I haven't checked to confirm that this flighted auger is the 5/8" thread size but I believe these are the pieces we have assembled
AMS Handle $132 - either a standard cross handle or a rachet: https://www.ams-samplers.com/18-ratcheting-cross-handle.html
AMS Extension $65 - you will be augering 2.6’ into the ground, so will want a 4’ extension at least: https://www.ams-samplers.com/5-8-x-4-extension.html
AMS flighted Auger $170: https://www.ams-samplers.com/1-1-4-x-18-triple-lead-flighted-auger-not-for-use-with-electric-hammer-drills.html

**Comment by ethansweep** [comment]
For AMS Extension: 
When I talked with Lindsey a while ago I told her to order a 3' extension for the auger. With a 4' extension you'll end up with an auger that's 5' tall, which is difficult to work with.
