### ISSUE TITLE
Serial USB terminal configuration

### ISSUE THREAD

**Issue by elhenriq** [precision-sustainable-ag/On-farm-Protocols#55]
I have tried to use the serial USB terminal app with multiple hotline callers and have found that the app has not been configured yet. We will have to configure the app individually for each person. The configuration is the same for everybody but has to be done per tablet not remotely.

**Comment by annabirnbaum** [comment]
"has to be done per tablet not remotely." - are you saying they will need to mail the tablet back to NCSU to have the app installed and that Sarah can't do it remotely?

Anna Paulk Birnbaum

Agricultural Specialist
UGA-Department of Crop and Soil Sciences
1420 Experiment Station Rd
Watkinsville, GA 30677
C: 404-889-1688
________________________________
From: elhenriq ***@***.***>
Sent: Wednesday, May 12, 2021 1:03 PM
To: precision-sustainable-ag/On-farm-Protocols ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [precision-sustainable-ag/On-farm-Protocols] Serial USB terminal configuration (#55)

[EXTERNAL SENDER - PROCEED CAUTIOUSLY]


I have tried to use the serial USB terminal app with multiple hotline callers and have found that the app has not been configured yet. We will have to configure the app individually for each person. The configuration is the same for everybody but has to be done per tablet not remotely.

**Comment by elhenriq** [comment]
I should have been more specific, it has to be done one by one. Definitely each tablet holder can do by themselves once I put together instructions that i am creating now.

**Comment by annabirnbaum** [comment]
ah, thanks for the clarification!

Anna Paulk Birnbaum

Agricultural Specialist
UGA-Department of Crop and Soil Sciences
1420 Experiment Station Rd
Watkinsville, GA 30677
C: 404-889-1688
________________________________
