### ISSUE TITLE
Access to other states sensors/devices on tech dashboard- hotline folks

### ISSUE THREAD

**Issue by annabirnbaum** [precision-sustainable-ag/On-farm-Protocols#56]
Can the hotline folks be given access to view other state's devices sensor data in the dashboard?  It would be helpful when troubleshooting via the hotline.

**Comment by screberg** [comment]
Good point.  changing now

Chris Reberg-Horton

Professor of Cropping Systems

University Faculty Scholar

Department of Crop and Soil Sciences, Campus Box 7620

NC State University

Raleigh, NC 27695-7620

919 515-7597

***@***.***
