### ISSUE TITLE
Node connect hotline call (text)

### ISSUE THREAD

**Issue by annabirnbaum** [precision-sustainable-ag/On-farm-Protocols#57]
Kansas contacted the hotline 5/12/21 @ 3:30pm

They had just installed sensors 90 mins ago and saw 3/4 nodes sent data to the dashboard twice, at 3:00 and 2:30, but one only sent data at 2:30.  Wanted to make sure everything was good before driving 2 hrs back.  I said that sometimes that happens and data will be sent later, but to be safe I suggested they reset everything, walked them through the pattern of gateway then nodes. 
After resetting, the one node didn't refresh on the dashboard so I walked through checking the node connection using the serial monitor on tablet.  They reported all nodes synched to gateway and asked if they should wait for the data to show up on dashboard.  I said it should be safe to drive home now without waiting.

**Comment by deannrp** [comment]
That same node at that site has again quit sending data. Will drive there as soon as I can to see what I can figure out. At that same site ( yrv) I am seeing some weird data from one sensor, reading 999 over and over. I'll check it out when I am there.

**Comment by annabirnbaum** [comment]
Deann's node 18000294 is still not connecting/ appearing in the tech dashboard (devices status) even though when I walked her through synching it using the serial monitor last week it showed that it had connected on the serial monitor after conducting a node scan.  
Do we have any other troubleshooting advice for this besides: reset, tighten antennae, wait and see?

@elhenriq

**Comment by annabirnbaum** [comment]
5pm on 5/18/21

Peter from Kansas went back to the site of 18000294 and found a broken solar panel connection in the node.  He was able to repair it and reset everything.  He said his tech dashboard hadn't updated since 12:05. I waited for the 5:05 update to come in on my computer and 18000294 did not come up in the data string.  I asked him to check the lights on the node, neither were on.  It sounds like this node needs to be replaced. 

Esleyther, @elhenriq is contacting Peter now

**Comment by elhenriq** [comment]
the node started to charge and i recomended him to just let it charge for the night since it was probably dead. will do a hard reset tomorrow.
