### ISSUE TITLE
Nebraska Sensor Issue

### ISSUE THREAD

**Issue by annabirnbaum** [precision-sustainable-ag/On-farm-Protocols#65]
Nebraska called around 5.  She was unsure if she needed to connect her tablet to the gateway to check if the installation was successful (i think video confusion). I walked her through checking on the dashboard on her phone.  We had to wait a few minutes for the gateway to come up, waited aa few more minutes for the nodes to show on dashboard (they didn't).  

I called Esleyther to see what to do next, I usually cheat and just plug into tablet to speed things along, I know we dont want new folks doing this.   Esleyther looked at her stuff on the dashboard and noticed the firmware was older.   He is going to keep an eye on it aand reach out to her if needed.  I told her she could drive home.

@ethansweep @elhenriq  Tomorrow (Ethan has my shift)  she was going to install the other set.  She asked if it would have the same issue, I looked at the firmware on that one.  last time it pinged the dashboard in march and it looked the same.  So I said hold off, but she is going to call the hotline tomorrow to check in.

**Comment by elhenriq** [comment]
i think that was a good call. easier to update in the office than field

**Comment by annabirnbaum** [comment]
4:15 5/21/21  Tawana and Esleyther updated the firmware in the lab today, she reinstalled in the field, its been 30 min and gateway hasn't connected to dashboard. Eslyether is giving her a call...
