### ISSUE TITLE
VA Tech (Blacksburg Team) sensors won't show up on Tech Dashboard

### ISSUE THREAD

**Issue by ethansweep** [precision-sustainable-ag/On-farm-Protocols#73]
VA Tech, Blacksburg team.

Called this morning while they were in the field to check if their gateway was sending data and showing up on the tech dashboard. She mentioned that they installed the sensors last week, but there wasn't anything on the tech dashboard about the gateway she was using. She also performed a hard reset of the system just before she called me to see if that resolved the issue, and it did not. She has also yet to submit the ODK sensor install form for this field.

I'm not sure why these sensors won't connect, and I told her that she made need to send them back. She also mentioned that she talked with @elhenriq recently about the issue. I asked her to text her email and phone number to the hotline so we could get back to her, but nothing has shown up yet.

Also, is the Blacksburg team VA1 or VA2 on the tech dashboard? @saseehav @brianwdavis

**Comment by elhenriq** [comment]
That was VA2, I was able to talk to them and get the gateways sending data, had to remotely connect to their tablet and control on Esper, there is bad cellular connectivity on that location the signal is really spotty. 
As of right now don't have a fix for that. Nodes seem to be working and collecting data.
