### ISSUE TITLE
AL 164676 Sending spotty data

### ISSUE THREAD

**Issue by annabirnbaum** [precision-sustainable-ag/On-farm-Protocols#75]
Kip called around 11.  Gateway 164676, we were working on this one yesterday too, is sending backlogs of data every few hours but not regularly.  He already reset everything a couple times.  I told him it is fine if all the data is there, just delayed (I havent looked closely to see if it is actually all there).

For this same farm, he hasnt submitted the sensor install form yet, because he is waiting to get the exact plant data from the farmer. Asked if he should wait or go ahead submit a comment on the form in the dashboard when he knows exact date.  He will go ahead and submit with estimated date and submit data comment later.

**Comment by annabirnbaum** [comment]
Meant to add, this gateway is showing it is connected to a cell tower in Riverdale, GA by ATL airport.  This is odd considering it is installed in south alabama and there are plenty of cell towers (i would think) between those two places,  Was this sim card in GA last year?  Could the data be spotty because it is trying to connect to a cell tower far way?  Why doesnt it pick one closer? Doesnt seem right.. @alondrathompson

**Comment by screberg** [comment]
Brian knows the details better, but I believe the story is that the
location of the cell phone tower is not always correct.  Its not a bug on
our end, the companies are not always keeping their location info up to
date.  I guess we need to put up some type of message now that we know.  We
found one that was reporting itself as being hundreds of miles away.  Given
that cells only go a few miles, we know that is not possible.

Chris


Chris Reberg-Horton

Professor of Cropping Systems

University Faculty Scholar

Department of Crop and Soil Sciences, Campus Box 7620

NC State University

Raleigh, NC 27695-7620

919 515-7597

***@***.***

**Comment by annabirnbaum** [comment]
Should we just get rid of that map then? Seems like it just confuses everyone.

Anna Paulk Birnbaum

Agricultural Specialist
UGA-Department of Crop and Soil Sciences
1420 Experiment Station Rd
Watkinsville, GA 30677
C: 404-889-1688
________________________________

**Comment by alondrathompson** [comment]
@annabirnbaum @screberg 
Yeah, the map can be confusing. There is no formal database with cell tower locations and info, so Hologram is pulling from a crowd sourced database that is incomplete which is why they label the point as approximate. I'll look closer at his data in a minute.

**Comment by alondrathompson** [comment]
![image](https://user-images.githubusercontent.com/52457672/120360582-e70b4f00-c2d6-11eb-8f17-67176c125c2e.png)
The reception is indeed spotty, but looks like it got worse after yesterday (5/31) afternoon. It's connected to a 2G tower which could be part of the issue but I'm not sure. The uploads do get longer though as they become more infrequent which could be impacting battery voltage. 

Kip could try raising the gateway a foot or two to see if he gets better reception that way.
