### ISSUE TITLE
Bag placement protocol needs to be updated for narrow row soybeans

### ISSUE THREAD

**Issue by brianwdavis** [precision-sustainable-ag/On-farm-Protocols#8]
Need to have a diagram to indicate how to cut a few plants and spread the bags apart in 7.5" beans, instead of together in a block.

**Comment by brianwdavis** [comment]
Need to assign @ethansweep with this one but it won't let me for some reason

**Comment by saseehav** [comment]
Testing work flow for on-farm issues. Sarah needs to follow up with Ethan about decomp bag placement in soybeans
