### ISSUE TITLE
Bare node not sending data

### ISSUE THREAD

**Issue by ethansweep** [precision-sustainable-ag/On-farm-Protocols#86]
Yesterday, after I got the gateway on one of our fields to connect to hologram, we noticed that one of the nodes wasn't sending data to Hologram. I inspected all of the cords and nothing appears to be damaged. 
I moved the cord on the node to the second inlet, instead of the first, and it was sending data to hologram for a while. This morning it's still sending data, but it's just a string of "999". Not sure what's happening, but I have to go back next week and I can take a look.

**Comment by elhenriq** [comment]
are all sensors reading 999?

**Comment by ethansweep** [comment]
@elhenriq Just one TDR Probe is sending 999, but it stopped doing that at 11:04 p.m on Sunday, June 6. Since then it's been sending actual numbers.
The field in question is gateway 1084044, and the node that's acting up is 18000351.
