### ISSUE TITLE
Nodes and Gateways software update

### ISSUE THREAD

**Issue by elhenriq** [precision-sustainable-ag/On-farm-Protocols#89]
DeAnn Presley from KS called today. We did a Zoom call and updated her nodes and gateways to the latest firmware update. Everything was successful. 

Also connected to the tablet to see the one of her gateways because it was not connecting to the network. We were able to get them working, but the nodes stop collecting data when the gateway stop communicating, this represents a big issue since we thought this was not a problem. The firmware that they had was 3.9, and we updated to 4.14 hope that will solve this last issue.

**Comment by annabirnbaum** [comment]
Have we established a protocol for people manually downloading data of the nodes at sites with consistent gateway issues?

@elhenriq Are you saying we need to program the nodes to forget the gateway in order for them to save data as we did last year at sites with bad/no cell service?  Seems like an urgent issue before folks start losing lots of data.

**Comment by alondrathompson** [comment]
@annabirnbaum @elhenriq I think the firmware update should take care of the problem with the nodes not collecting. That was probably the issue with the alarms that the update fixes. 

For manually downloading data, the first option is to get the data off of the gateway’s SD card. They should use an SD card reader instead of the menu. Only if that doesn’t work or doesn’t have all the node data should someone then connect directly to a node. Printing data from the node is slow and saving it nuanced.

**Comment by saseehav** [comment]
@alondrathompson @elhenriq how can we test if the nodes are saving data? Can we get help with this issue?

**Comment by elhenriq** [comment]
@annabirnbaum like @alondrathompson with the latest update which everybody has now this shouldn't be a problem. 
@saseehav the only way to get data and see if they are working is to connect to the nodes and manually print it to the serial port and then copy all of it. 

I did it for this farm because I had the suspicion the 3.9 software had that problem and that confirmed it. As for a protocol to do manual collection, I don't think we should do it!

**Comment by saseehav** [comment]
@alondrathompson select 3 sites where gateways have come on and off/ lost connection, and do a manual check to confirm that A) the sd card is collecting an entire set of data from the nodes and B) manual check the nodes for saving data as well, in case the sd card is not whole

**Comment by alondrathompson** [comment]
@saseehav I'm not sure I understand your last comment. Are you asking me to pick 3 sites and work with the technicians to check for the data? Or are you laying out the steps for a protocol and asking for confirmation?

**Comment by saseehav** [comment]
@alondrathompson yes, please try to find 3 or so sites, yours or someone else's that have had gateway communication go down for a period of time, or gateways that connect but cannot seem to get a message from the nodes, and confirm that either the sd card has all the data, or if not, that the data exists on the nodes. We don't have evidence that it does yet. One example might be UAN - farm in GA - gateway sent a message at start up May 25, then went down until today. One node never transmitted anything. I am not convinced the data is there from that time period.

**Comment by alondrathompson** [comment]
Ok. I'll need help from @elhenriq @annabirnbaum and/or @ethansweep to find sites and get data from them. I'm not actually involved in the installation of the MD sets and neither do I have any tests of my own running right now. 

Esleyther, Anna, and Ethan: I don't want to add an extra burden to you, so if you have such a site close by or are going to visit such a site anyway, let me know. If you are able to download the data and send it to me, I'll check it for missing dates and such.  

@saseehav Is this how you were envisioning we do this?

**Comment by elhenriq** [comment]
I see what I can do

**Comment by annabirnbaum** [comment]
okay, i'll work on this.  Don't pay too much attention to UAN, it is from the winter testing, at a UGA farm, running old firmware and that one node needs a new antennae.

Anna Paulk Birnbaum

Agricultural Specialist
UGA-Department of Crop and Soil Sciences
1420 Experiment Station Rd
Watkinsville, GA 30677
C: 404-889-1688
________________________________
