### ISSUE TITLE
AL 164678 (Snead) 

### ISSUE THREAD

**Issue by annabirnbaum** [precision-sustainable-ag/On-farm-Protocols#90]
Kip called me directly: Gateway 164678 battery drained to 3.76 and stopped sending data on 6/1/21.  All the wiring looks fine. This gateway he has had a hard time send consistent data since installation.  Last week he tried driving it to town using celling scouting mode and didn't pick up signal.  He had one at this field last year that worked?  I suggested the battery may have drained faster than it charged if it was constantly trying to connect to cellular. He has already tried raising the gateway.  

@elhenriq is it time to send a replacement gateway?

**Comment by annabirnbaum** [comment]
Some data came through on the gateway last night, but it is from 5/31/21. Hasn’t sent data since 3am (it’s 11am) now.

**Comment by elhenriq** [comment]
I'm not sure a replacement gateway will solve the issue. Also we don't have replacements
