### ISSUE TITLE
GA (280923)

### ISSUE THREAD

**Issue by annabirnbaum** [precision-sustainable-ag/On-farm-Protocols#97]
testing out 280923 at my house today before taking to field tomorrow.  In Athens, cell service definitely not issue.

11;20am turned on nodes, then gateway, checked dashboard - not online
11:40 am still not online
11:45 connected tablet to gateway and let it go through initialization process : comes online to  dashboard immediately 

**I know I've asked this before but do we need to make it standard protocol to connect gateway to tablet at installation?  Do they ever come online without connecting to tablet.  In my experience, no.**  @saseehav @elhenriq

**Comment by elhenriq** [comment]
im having the same suspicion, i have some that connect without needed the tablet but it could be because we test here prior
