### ISSUE TITLE
Device 280915 (NE) sending same data 

### ISSUE THREAD

**Issue by alondrathompson** [precision-sustainable-ag/On-farm-Protocols#98]
Brian noticed partial strings coming from this device. As I scrolled through the data I noticed the same timestamps coming up over and over. I downloaded data from June 1st to today and confirmed that the same strings are getting sent, ex) timestamp 2021-6-2_22:15:00_UTC shows up **63** times from the same node. 

I think there may be an issue with the SD card, that the dump file is not deleting after each upload so all the old data gets sent with every upload. @elhenriq or @annabirnbaum Can we ask this technician to replace the SD card? I don't know if this will fix the issue, but it's a first step.

![Dev280915 Error](https://user-images.githubusercontent.com/52457672/121404920-6f6a9f00-c92a-11eb-98f3-9ac12cabb003.png)

**Comment by elhenriq** [comment]
do they need to replace with a new one or just take out and back in?

**Comment by alondrathompson** [comment]
They could try taking it out and putting it back in first, and then replace it if that doesn't work. I don't think I've seen this behavior before, so I don't really know how to fix it.
