### ISSUE TITLE
MN needs cords

### ISSUE THREAD

**Issue by annabirnbaum** [precision-sustainable-ag/On-farm-Protocols#99]
Ethan Ley contacted the hotline.  He noticed his gateways haven't connected to the dashboard.

1. asked if he needs to set up appt to troubleshoot- i said no, just contact hotline during the hours when at farm
2. asked if needs cables to connect to gateway to troubleshoot-  i said YES, but he cannot find them

@elhenriq @saseehav Do yall have a set of cords (tablet to gateway/nodes)  you can send to MN ASAP?

**Comment by elhenriq** [comment]
sarah has the cables that goes with that.
